### ISSUE TITLE
push notification module doesn't work

### ISSUE THREAD

**Issue by rchen9012** [BelledonneCommunications/flexisip#1]
compiled source with  ./configure --enable-pushnotification,  sip invite waited for more than 5 seconds nothing happened.

[module::PushNotification]
enabled=true
filter=
timeout=5
max-queue-size=10
apple=true
apple-certificate-dir=/usr/local/etc/flexisip/apns
google=true
google-projects-api-keys=[REDACTED]
windowsphone=true
no-badge=false
external-push-uri=
external-push-method=GET

**Comment by Gui13** [comment]
I removed your private key from your post. You should never post that private information here. I suggest you reset your API key at Google. 

As for your problem, enable debug mode and try to understand from the logs:

    [global]
    debug=true

Otherwise post them in the mailing list: https://lists.gnu.org/mailman/listinfo/flexisip-developers 
We read mostly the mailing list.

**Comment by rchen9012** [comment]
thx for replying.   I am trying to compile with boost log  but failed,  both boost_1.59.0  and boost_1.49.0 has the same error.

/usr/bin/xsd cxx-tree --generate-wildcard --generate-serialization --generate-ostream --generate-detach --std c++11 --type-naming java \
--function-naming java  --location-regex-trace --location-regex "%http://.+/(.+)%\$1%" --output-dir .  fthttp.xsd
  CXX    fthttp.lo
  CXXLD  libxml_binding_generated.la
make[4]: Leaving directory `/usr/local/src/flexisip/src/xml'
Making all in presence
make[4]: Entering directory `/usr/local/src/flexisip/src/presence'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/usr/local/src/flexisip/src/presence'
Making all in tclap
make[4]: Entering directory `/usr/local/src/flexisip/src/tclap'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/usr/local/src/flexisip/src/tclap'
make[4]: Entering directory `/usr/local/src/flexisip/src'
  CXX    log/libhack_a-workaround.o
  AR     libhack.a
  CXX    main.o
  CXX    flexisip-exception.o
flexisip-exception.cc: In function ‚Äòvoid uncaught_handler()‚Äô:
flexisip-exception.cc:28:283: error: no match for ‚Äòoperator<<‚Äô in ‚Äòboost::log::v2_mt_posix::aux::make_record_pump(LoggerT&, boost::log::v2_mt_posix::record&) [with LoggerT = boost::log::v2_mt_posix::sources::severity_logger_mt<flexisip::log::level>]((* & _boost_log_record_28)).boost::log::v2_mt_posix::aux::record_pump<LoggerT>::stream [with LoggerT = boost::log::v2_mt_posix::sources::severity_logger_mt<flexisip::log::level>, typename LoggerT::char_type = char]() << e‚Äô

**Comment by Gui13** [comment]
No need to use boost_log, the standard logging facility suffices.

**Comment by rchen9012** [comment]
standard log has not push notification debug detail 

[global]
debug=true
log-filter=%Severity% > debug
dump-corefiles=true

**Comment by rchen9012** [comment]
push notification no log and still not work

**Comment by ReisBenjamin** [comment]
Can you try up to date code and reopen this issue if it's still happening ?
Please see how to use new SDK here : https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/

Thanks

**Comment by meetme2meat** [comment]
@ReisBenjamin Can we reopen this issue again even with the latest code the flexisip push notification does not work.
