### ISSUE TITLE
how I use TCP for message and UDP for calling in linphone?

### ISSUE THREAD

**Issue by prashantvidja** [BelledonneCommunications/flexisip#10]
Hello,

I use Linphone as sip-client with kamailio+flexisip VoIP system.
I forward all request from flexisip to kamailio By Forward module.
**how I use TCP transport for messaging and calling for UDP transport?**

Thanks

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you still need an answer to your question, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
