### ISSUE TITLE
flexisip-error-DoSProtection: '/sbin/ip6tables -w -F FLEXISIP-DOS-PROTECTION 2>&1' failed with output 'ip6tables: No chain/target/match by that name.

### ISSUE THREAD

**Issue by willnaoosmith** [BelledonneCommunications/flexisip#105]
(I know it's probably a dumb question)

I already created a chain called `FLEXISIP-DOS-PROTECTION`

```
~$ sudo iptables -N FLEXISIP-DOS-PROTECTION
iptables: Chain already exists.
```

It's there another command i need to run?

log:

```
2020-09-10 10:07:47:249 bctbx-message-Starting flexisip proxy-server version 2.0.0-2-g608aa1b
2020-09-10 10:07:47:274 flexisip-error-DoSProtection: '/sbin/iptables -w -F FLEXISIP-DOS-PROTECTION 2>&1' failed with output 'iptables: No chain/target/match by that name.'.
2020-09-10 10:07:47:277 flexisip-error-DoSProtection: '/sbin/ip6tables -w -F FLEXISIP-DOS-PROTECTION 2>&1' failed with output 'ip6tables: No chain/target/match by that name.
```

**Comment by tjfayaz** [comment]
Exactly the same problem here. Any updates?

**Comment by willnaoosmith** [comment]
nope, none

**Comment by RaddishIoW** [comment]
I noticed that it was calling "/sbin/iptables", but on my Debian 10 machine `whereis iptables` reports it being in `/usr/sbin/iptables`... A clue?

**Comment by avalanche15** [comment]
> (I know it's probably a dumb question)
> 
> I already created a chain called `FLEXISIP-DOS-PROTECTION`
> 
> ```
> ~$ sudo iptables -N FLEXISIP-DOS-PROTECTION
> iptables: Chain already exists.
> ```
> 
> It's there another command i need to run?
> 
> log:
> 
> ```
> 2020-09-10 10:07:47:249 bctbx-message-Starting flexisip proxy-server version 2.0.0-2-g608aa1b
> 2020-09-10 10:07:47:274 flexisip-error-DoSProtection: '/sbin/iptables -w -F FLEXISIP-DOS-PROTECTION 2>&1' failed with output 'iptables: No chain/target/match by that name.'.
> 2020-09-10 10:07:47:277 flexisip-error-DoSProtection: '/sbin/ip6tables -w -F FLEXISIP-DOS-PROTECTION 2>&1' failed with output 'ip6tables: No chain/target/match by that name.
> ```

hey,u  have sloved this problem ?

**Comment by willnaoosmith** [comment]
> hey,u have sloved this problem ?

I didn't. I ended up quitting my old job.
