### ISSUE TITLE
RTP traffic from local client to public client

### ISSUE THREAD

**Issue by AlexSSP** [BelledonneCommunications/flexisip#106]
Hi. My flexisip with back-end Asterisk have local (10.178.0.6) and public IP address. Clients wrom WAN and LAN registred very well. But RTP traffic from local client is trying to go to the public IP my flexisip.

=====================
[global]
log-level=debug
aliases=sip-dev.ru localhost
transports=sip:0.0.0.0:5070
enable-snmp=false

[module::Authentication]
enabled=false

[module::Registrar]
max-expires=604800
enabled=true
reg-domains=sip-dev.simdev.ru
reg-on-response=true
redis-server-domain=127.0.0.1
redis-server-port=6379
redis-auth-password=flexisip
db-implementation=redis

[module::Router]
enabled=true
fork-late=true
message-delivery-timeout=604800

[module::MediaRelay]
enabled=true
filter=
nortpproxy=nortpproxy
sdp-port-range-min=10000
sdp-port-range-max=10500
bye-orphan-dialogs=false
max-calls=0
force-relay-for-non-ice-targets=true
prevent-loops=true
early-media-relay-single=true
max-early-media-per-call=0
inactivity-period=3600
force-public-ip-for-sdp-masquerading=false

[module::PushNotification]
enabled=true
timeout=5
firebase=true
firebase-projects-api-keys=924566835:AAAA10R13ds:APA91bGofRCNOmSwrUJpbgE4qLeueKsxrKmPXVSJ2xIXdM_2C7W6__aj2QypL9Qd7n8JX04Z0jHu1px0TNWF8Hg5Cr2Isua2NSWfwjR
retransmission-count=3
retransmission-interval=5
display-from-uri=true
external-push-uri=http://127.0.0.1/send-push?type=$type&token=$token&api-key=$api-key&app-id=$app-id&from-name=$from-name&from-uri=$from-uri&from-tag=$from-tag&to-uri=$to-uri&call-id=$call-id&event=$event&soun$

[module::Forward]
enabled=true
filter=
route=sip:10.178.0.6:5060
add-path=true
rewrite-req-uri=true
default-transport=udp
params-to-remove=pn-tok pn-type app-id pn-msg-str pn-call-str pn-call-snd pn-msg-snd pn-timeout

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
