### ISSUE TITLE
Flexisip proxy connection error - No credentials matched realm  or no realm

### ISSUE THREAD

**Issue by yuvi7777** [BelledonneCommunications/flexisip#108]
Server set up however getting connection error - No credentials matched realm  or no realm. In our case database is connecting but while register from linphone its giving authentication issue.
Any suggestions please

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
