### ISSUE TITLE
RTP connection not established when using IPv4

### ISSUE THREAD

**Issue by gzdes** [BelledonneCommunications/flexisip#111]
We are having issues with SIP calls when using IPv4 with sip.linphone.org. 

RTP streams cannot be established because the INVITE SDP only contains an IPv6 address. The 200 Ok answer seems to contain the IP4 address, as expected.
If I enable ICE an stun on the caller, it seems to work. But as long as I disable ICE, the stream fails with incorrect family.

I think the IP family detection has been broken, probably on commit 2caed30c8aebb7233ac7384eb438644ebad19a5b

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
