### ISSUE TITLE
Fix for eventlogs.cc and presence-server.cc errors if Soci disabled

### ISSUE THREAD

**Issue by jamesshuriff** [BelledonneCommunications/flexisip#112]
In src/eventlogs/eventlogs.cc there is an #if ENABLE_SOCI block that contains the closing bracket for "namespace flexisip". If Soci is not enabled the closing bracket will not be parsed and the compiler will raise an error.

In src/presence/presence-server.cc there is a variable "const string &connectionString" that is not used if Soci is disabled, raising -Werror=unused-variable.

I have attached a patch that will fix these issues.

[flexisip.patch.txt](https://github.com/BelledonneCommunications/flexisip/files/6176492/flexisip.patch.txt)

**Comment by ComradeSlice** [comment]
Please respond.
