### ISSUE TITLE
Project requires sofia-sip 1.13.11 when 1.13.3 is the latest version

### ISSUE THREAD

**Issue by yurivict** [BelledonneCommunications/flexisip#114]
```
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find SofiaSipUa: Found unsuitable version "1.13.3", but required
  is at least "1.13.11" (found /usr/local/include/sofia-sip-1.13)
```

See https://github.com/freeswitch/sofia-sip/tags

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
