### ISSUE TITLE
Flexi SIP - VoIP Push on IOS 14

### ISSUE THREAD

**Issue by Omid-Mohajerani** [BelledonneCommunications/flexisip#115]
Hi,

Is Flexi SIP Puh gateway working with IOS 14? I have an asterisk as my telephony system and I want to run Flexi server for Push Notification for IOS. As VoIP Push is working differently now I want to know is Flexi SIP Server can send VoIP push with the latest IOS? 

Thanks

**Comment by simon6329** [comment]
Yes, Flexisip can send VoIP push with the latest IOS.

**Comment by Omid-Mohajerani** [comment]
Yes, thanks @simon6329. Working on latest IOS
