### ISSUE TITLE
not able to register with other custom port

### ISSUE THREAD

**Issue by prashantvidja** [BelledonneCommunications/flexisip#12]
Hello

I am not able to register with other port. Only I able to register with 5060 port.
i change flexisip port 5080 by change transport by below

> Transport=sip:*:5080

How can  I connect with 5080 port only i connect with default port.

Thanks

**Comment by GeorgeMina** [comment]
Any solution to this?

**Comment by prashantvidja** [comment]
Yes, it worked for me. I think I had a different issue in the configuration.

**Comment by GeorgeMina** [comment]
> Yes, it worked for me. I think I had a different issue in the configuration.
> But I did not remember exactly what was the issue.

Thanks for replying to this old thread. If there's any additional info you can provide at all, that would be helpful; otherwise, thanks for letting me know.
