### ISSUE TITLE
Registrar expires much earlier than the high max/min value

### ISSUE THREAD

**Issue by sanjayws** [BelledonneCommunications/flexisip#120]
Hello.

I've set the registrar 

max-expires = 6048000
min-expires =6048000

Yet i am losing registration until the phone app is launched again and a reregistration is done again. Of course, this is needed for push notification, otherwise it will not invoke the pusher at all (right?).

Any advice is appreciated. 

Thanks
Sanjay

**Comment by sanjayws** [comment]
Solved this too

**Comment by jsonsolanki** [comment]
Hello @sanjayws 

Can you please tell me how you resolve this issue?

Thanks

**Comment by sanjayws** [comment]
Hi @jsonsolanki 

The expiry comes from many places, it can be set on the softphone, in Flexisip and also the backend. From testing, its however best to set it on the actual pbx/registration server. We use Asterisk and we set the min and max to highest possible values acceptable, in my case i've set it 604800 seconds.

**Comment by jsonsolanki** [comment]
Hii @sanjayws 

In, Our pbx/registration server, we have expiry time 60 and we are not able to change it. So we want to send sip registration request from flexisip to pbx/registration server after every 60 seconds. 

thanks
