### ISSUE TITLE
can't install flexisip on centos 7.

### ISSUE THREAD

**Issue by LeAnhlinux** [BelledonneCommunications/flexisip#123]
Hello sir,

I try install following https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/1.%20Installation/ the have error: 

--> Finished Dependency Resolution
Error: Package: bc-liblinphone-4.5.16-1.el7.x86_64 (Belledonne-stable)
           Requires: libbellesip.so.1()(64bit)
Error: Package: 1:bc-flexisip-2.0.4-1.el7.x86_64 (Belledonne-stable)
           Requires: liblinphone++.so.9()(64bit)
           Available: bc-liblinphone-4.3.0-1.el7.x86_64 (Belledonne-stable)
               liblinphone++.so.9()(64bit)
           Available: bc-liblinphone-4.3.1-1.el7.x86_64 (Belledonne-stable)
               liblinphone++.so.9()(64bit)
           Available: bc-liblinphone-4.3.2-1.el7.x86_64 (Belledonne-stable)
               liblinphone++.so.9()(64bit)
           Available: bc-liblinphone-4.3.3-1.el7.x86_64 (Belledonne-stable)
               liblinphone++.so.9()(64bit)
           Installing: bc-liblinphone-4.5.16-1.el7.x86_64 (Belledonne-stable)
              ~liblinphone++.so.10()(64bit)
Error: Package: 1:bc-flexisip-2.0.4-1.el7.x86_64 (Belledonne-stable)
           Requires: libortp.so.14()(64bit)
           Available: 1:bc-ortp-4.3.0-1.el7.x86_64 (Belledonne-stable)
               libortp.so.14()(64bit)
           Available: 1:bc-ortp-4.3.1-1.el7.x86_64 (Belledonne-stable)
               libortp.so.14()(64bit)
           Available: 1:bc-ortp-4.3.2-1.el7.x86_64 (Belledonne-stable)
               libortp.so.14()(64bit)
           Available: 1:bc-ortp-4.3.3-1.el7.x86_64 (Belledonne-stable)
               libortp.so.14()(64bit)
           Installing: 1:bc-ortp-4.5.15-1.el7.x86_64 (Belledonne-stable)
              ~libortp.so.15()(64bit)
Error: Package: 1:bc-flexisip-2.0.4-1.el7.x86_64 (Belledonne-stable)
           Requires: libmediastreamer.so.10()(64bit)
           Available: bc-mediastreamer-4.3.0-1.el7.x86_64 (Belledonne-stable)
               libmediastreamer.so.10()(64bit)
           Available: bc-mediastreamer-4.3.1-1.el7.x86_64 (Belledonne-stable)
               libmediastreamer.so.10()(64bit)
           Available: bc-mediastreamer-4.3.2-1.el7.x86_64 (Belledonne-stable)
               libmediastreamer.so.10()(64bit)
           Available: bc-mediastreamer-4.3.3-1.el7.x86_64 (Belledonne-stable)
               libmediastreamer.so.10()(64bit)
           Installing: bc-mediastreamer-4.5.16-1.el7.x86_64 (Belledonne-stable)
              ~libmediastreamer.so.11()(64bit)
Error: Package: 1:bc-flexisip-2.0.4-1.el7.x86_64 (Belledonne-stable)
           Requires: liblinphone.so.9()(64bit)
           Available: bc-liblinphone-4.3.0-1.el7.x86_64 (Belledonne-stable)
               liblinphone.so.9()(64bit)
           Available: bc-liblinphone-4.3.1-1.el7.x86_64 (Belledonne-stable)
               liblinphone.so.9()(64bit)
           Available: bc-liblinphone-4.3.2-1.el7.x86_64 (Belledonne-stable)
               liblinphone.so.9()(64bit)
           Available: bc-liblinphone-4.3.3-1.el7.x86_64 (Belledonne-stable)
               liblinphone.so.9()(64bit)
           Installing: bc-liblinphone-4.5.16-1.el7.x86_64 (Belledonne-stable)
              ~liblinphone.so.10()(64bit)

any ideal to solve this problem ?

**Comment by ping203** [comment]
edit /etc/yum.repos.d/BelledonneCom.repo  , only insert [Belledonne-stable]
[Belledonne-stable]
name=Belledonne-stable
baseurl=http://www.linphone.org/snapshots/centos/$releasever/stable
enabled=1
gpgcheck=0
