### ISSUE TITLE
push gateway and push server

### ISSUE THREAD

**Issue by M-Stenzel** [BelledonneCommunications/flexisip#124]
Hi team,

I successfully use the combination of flexisip & linphone - solid rock!
Now I want to optimise. Using the combination of flexisip push gateway and a push server is promising.
I was not able to squeeze information from the WWW, because of that I am asking here:
I do not want to use any Google, Apple, Firebase, etc. push server (security concerns).
Is it possible to use a self hosted push server (which one, "gotify" an option?) for that?
How to set up?

Thanks for clarifying,

Martin.

**Comment by asadcr** [comment]
@M-Stenzel Would you be able to share your flexisip config and version. i am unable to setup it as push gateway. 

To answer your question, yes Flexisip supports external push, you can setup your own server and flexisip will forward requests there. U need to modify you apps as well to receive the pushes

**Comment by M-Stenzel** [comment]
@asadcr 
Well, you can find it here:

[https://www.xy-space.de/owncloud/index.php/s/gnf4d3Wc7XeLh2x](https://www.xy-space.de/owncloud/index.php/s/gnf4d3Wc7XeLh2x)

Regards, Martin.

**Comment by asadcr** [comment]
@M-Stenzel Does't work for me. I have the similiar config. almost identical. How do u get it to connect to backend server ? I am using Asterisk.

**Comment by Failxxx** [comment]
Here is the documentation: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/A.%20Configuration%20Reference%20Guide/2.3.4/module/PushNotification
See `external-push-uri`.

Sincerely,
Félix.
