### ISSUE TITLE
Inserting contact to Redis  fails

### ISSUE THREAD

**Issue by OmanCoding** [BelledonneCommunications/flexisip#125]
Hi,

when trying the following contact,
```
4054k50_R101
```
```
<sip:101@10.22.22.48:57937;transport=udp>;q=1;expires=300;avaya-actions="presence.initiate-pubsub,presence.redirect";+avaya.gmtoffset="3:00";+avaya.js-ver="1.0";+avaya.model="J139";+avaya.sn="19WZ49200GJK";+avaya.firmware="4.0.5.0.10";+av.ip.mode=4;+av.sdp.anat;+av.sip.sig=4;+av.sip.media=4;+av.sip.iptolerance;+sip.instance="<urn:uuid:00000000-0000-1000-8000-c81feabef2aa>";reg-id=1
```

it does not succeed, however,
when the contact storage is set to internal, it works

is it that the contact string contains non allowed characters by Redis?

regards

**Comment by smrdoshi** [comment]
Hi @OmanCoding 

Have you got any solution to make it work with Redis? 

Thanks

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
