### ISSUE TITLE
Flexisip error

### ISSUE THREAD

**Issue by varunbyakod** [BelledonneCommunications/flexisip#127]
| -- Found XercesC: /home/varun/linphone/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/flexisip/git_e8cb0ee4e3d5cf3710c5c6cf7c2230b013a36576-r0.0/recipe-sysroot/usr/lib/libxerces-c.so (found version "3.1.4")
| -- Found LibXsd: /home/varun/linphone/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/flexisip/git_e8cb0ee4e3d5cf3710c5c6cf7c2230b013a36576-r0.0/recipe-sysroot/usr/include;/home/varun/linphone/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/flexisip/git_e8cb0ee4e3d5cf3710c5c6cf7c2230b013a36576-r0.0/recipe-sysroot/usr/include
| -- Looking for arc4random
| -- Looking for arc4random - not found
| -- GCC version 9.3.0 should have steady_clock
| -- Soci found: Looking for plugins
| --     * Plugin mysql not found.
| --     * Plugin odbc not found.
| --     * Plugin postgresql not found.
| --     * Plugin sqlite3 found /home/varun/linphone/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/flexisip/git_e8cb0ee4e3d5cf3710c5c6cf7c2230b013a36576-r0.0/recipe-sysroot/usr/lib/libsoci_sqlite3.so.
| CMake Error at cmake/FindSoci.cmake:87 (MESSAGE):
|   Required component mysql not found.  It seems that Soci was built without
|   support of mysql, consider rebuilding it.
| Call Stack (most recent call first):
|   CMakeLists.txt:197 (find_package)
|
|
| -- Found Soci: /home/varun/linphone/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/flexisip/git_e8cb0ee4e3d5cf3710c5c6cf7c2230b013a36576-r0.0/recipe-sysroot/usr/include/soci
| -- MSGPACK not found
| -- Found OpenSSL: /home/varun/linphone/build-raspberrypi-rdk-broadband/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/flexisip/git_e8cb0ee4e3d5cf3710c5c6cf7c2230b013a36576-r0.0/recipe-sysroot/usr/lib/libcrypto.so (found suitable version "1.1.1j", minimum required is "0.9.8")
| -- The following OPTIONAL packages have been found:
|
|  * Threads
|  * XercesC
|  * LibXsd
|  * PkgConfig
|
| -- The following REQUIRED packages have been found:
|
|  * SofiaSipUa (required version >= 1.13.11)
|  * ortp (required version >= 0.21)
|  * bctoolbox (required version >= 0.0.3)
|  * belr
|  * Mediastreamer2 (required version >= 2.9.0)
|  * BelleSIP (required version >= 1.2.4)
|  * Linphone
|  * LinphoneCxx
|  * Soci
|  * OpenSSL (required version >= 0.9.8)

When i gave bitbake flexisip command,it is throwing me the above error.Even i tried to install these 2 packages(libmysqlclient-dev and libsoci-dev) in home directory and also via flexisip.inc file,but still facing the same errors.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
