### ISSUE TITLE
Push Notification on Android device

### ISSUE THREAD

**Issue by inoutglobal** [BelledonneCommunications/flexisip#129]
Dears,

I am trying to test Push Notification on Android device, but i dont know where to retreive device_push_token as described in this: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Push%20notifications/

![image](https://user-images.githubusercontent.com/47820627/133681240-33d54164-21bf-4543-b12e-9e569f718db6.png)

**Comment by errno** [comment]
As for me, the easiest way is to get it from the "Contact" field of the registration request, which is logged to flexisip-proxy log if debugging enabled.

**Comment by inoutglobal** [comment]
You nailed it. Thanks. By the way, is there any flexisip/linphone forum or community? I have other doubts and i think this not the right place to do it.

**Comment by errno** [comment]
There is a [FlexiSIP Develepers maling list](https://lists.gnu.org/mailman/listinfo/flexisip-developers). Questions about FlexiSIP could be asked there.

P.S. If your question is answered, don't forget to close the issue.

**Comment by inoutglobal** [comment]
Thanks so much!
