### ISSUE TITLE
The file user.db can't be used to store user. 

### ISSUE THREAD

**Issue by yuanlida** [BelledonneCommunications/flexisip#13]
1.I can't get user from user.db file.
2.I am trying to set up my server on AWS server, But when make some call, I will see this logs:

2017-12-01 06:57:54:410 ortp-message-RtpSession bound to [172.31.1.211] ports [65152] [65153]
2017-12-01 06:57:54:410 ortp-message-RtpSession bound to [172.31.1.211] ports [16396] [16397]
2017-12-01 06:57:54:410 ortp-message-RtpSession bound to [172.31.1.211] ports [50022] [50023]
2017-12-01 06:57:54:410 ortp-message-RtpSession bound to [172.31.1.211] ports [31532] [31533]

**Comment by yuanlida** [comment]
I have set all filter  to true in the flexisip config file,but the nat and relay can not work well.

**Comment by ReisBenjamin** [comment]
You need to set 

db-implementation=file
datasource=/Your/Path/To/user.db

in [module::Authentication]

**Comment by wmukhtar** [comment]
I have exactly the same issue, tried changing to following but still same error:

in [module::Authentication]
db-implementation=file
datasource=/Your/Path/To/user.db

**Comment by wmukhtar** [comment]
we created above file and kept 'version 1' in line 1 and then we have started receiving following error message with above configuration:

2018-06-11 20:01:38:184 flexisip-users-error-Registration failure, password did not match

**Comment by johnma** [comment]
it looks like this


![image](https://user-images.githubusercontent.com/5801145/41503959-a32c1b5a-7213-11e8-9d77-37ca332d4656.png)

**Comment by Failxxx** [comment]
Hello,
Thank you for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
