### ISSUE TITLE
pusher: support for provider unifiedpush

### ISSUE THREAD

**Issue by alien999999999** [BelledonneCommunications/flexisip#130]
even though no iOS, it would be still great to support unifiedpush as a provider (particularly the NoProvider2Push distributor seems quite interesting) (also support needed on linphone for android)

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
