### ISSUE TITLE
Flexisip 2.1.0-beta as Push Gateway doesn't talk to backend server

### ISSUE THREAD

**Issue by bkiziuk** [BelledonneCommunications/flexisip#131]
I'm trying to configure Flexisip (2.1.0-beta-18-g25c8f3c8) to act as a front-end Proxy server with Push Gateway function for the back-end FreePBX 15 server.

Before, I had successfully tested the installation for [a single domain](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Deploy%20Flexisip%20for%20one%20domain/) - I configured Android LinPhone with TLS transport and was able to register.

Then I removed the configuration, stopped both MariaDB and Redis daemons and followed the guide [here](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/).
As I can understand the various descriptions, the Flexisip should accept incoming connection and then forward the REGISTER request to the back-end server which address is found in SIP REGISTER message.
At the moment the push services (Firebase and Apple) are not defined as at the first stage I want to make the Proxy working.

The current result is that: when I run Android LinPhone app, it shows as registered on Flexisip, but no communication is exchanged between the front-end (sip.mydomain.com) and the back-end (pbx.mydomain.com). These are on different subnets (DMZ and LAN) but of course the routing is correct and no traffic is blocked between them.
pbx.mydomain.com is resolvable to IP address using '/etc/hosts' at the moment.

The current configuration and the debug log is attached.
In the log, next to the SIP dump I can also see some garbage which I suspect is not right as well.
The installation is made on Debian 10 (Buster) from the repository.

[flexisip.log.txt](https://github.com/BelledonneCommunications/flexisip/files/7379592/flexisip.log.txt)
[flexisip.conf.txt](https://github.com/BelledonneCommunications/flexisip/files/7379596/flexisip.conf.txt)

**Comment by LucasfoliveiraSe** [comment]
Same problem , i have studies rfc 3608 but it not seens to work when a I use service-route on flexisip.conf in the registrar module.

**Comment by E2-Sterlin** [comment]
can anyone please share those configuration ,I am trying the same .

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
