### ISSUE TITLE
Module registrar service-route not working properly

### ISSUE THREAD

**Issue by LucasfoliveiraSe** [BelledonneCommunications/flexisip#136]
Hi guys , in my scenario i am trying to integrate an existent asterisk server to flexisip , having the asterisk as a backend server, I used in ther registrar module the statement service-route = sip:sip.example.com , i expected tha it would work like is described in the rfc3608 , but it is ignore and tryes to atuthenticate on flexisip as usual. Anyone can help me out with this issue.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
