### ISSUE TITLE
Getting no such file or directory Error While creating dump file with following command on centos 7

### ISSUE THREAD

**Issue by beartandgibsondev** [BelledonneCommunications/flexisip#138]
sudo /opt/belledonne-communications/bin/flexisip --dump-default all > /etc/flexisip/flexisip.conf
-bash: /etc/flexisip/flexisip.conf: No such file or directory

**Comment by Failxxx** [comment]
Hello,
The file is now shipped with Flexisip (>= 2.3) on installation.
Reference: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/1.%20Installation/

Sincerely,
Félix.
