### ISSUE TITLE
Flexisip Proxy requests itself for inbound call request.

### ISSUE THREAD

**Issue by IntuzHiteshK** [BelledonneCommunications/flexisip#139]
Hi,

We are trying to configure Flexisip Proxy and Push notification service to wake our client (softphone) from the background when an inbound call arrives. The registration request and outbound call seem fine through the proxy but when there is an inbound call routed from PBX to flexisip but the proxy (Flexisip) fails to forward the request back to the end-user instead it keeps requesting its own IP until there are too many hops and then it dies.

We have confirmed the headers for end-user's IP it seems fine,
PJSIP/889xxx/sip:889xxx@54.144.xx.xx:5060;x-ast-orig-host=27.61.xxx.xxx:59699

------ Logs (Capture Sanitized) ------

[capture_sanitized.log](https://github.com/BelledonneCommunications/flexisip/files/8667658/capture_sanitized.log)

------ Logs Till here -----------------

As you can see the error 483: Too many hops.

Can you please guide what could be the issue?

Thanks

**Comment by E2-Sterlin** [comment]
@IntuzHiteshK HI I am also trying to do the same setup using Asterisk and Flexisip, is it possible to share the configuration file of flexisip and Asterisk?

**Comment by gcareri** [comment]
Hi @IntuzHiteshK,
Did you find a solution?
Thanks in advance

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
