### ISSUE TITLE
Accept through TLS transport & Forward with TCP

### ISSUE THREAD

**Issue by prashantvidja** [BelledonneCommunications/flexisip#14]
Hello

I am using flexisip as a Proxy server with kamailio and linphone.
I want to accept all request through TlS transport and Foward this request by TCP transport in Forward Module ?
I did some tests but I am not able to register kamailio.
please help,.,,,

Thanks

**Comment by prashantvidja** [comment]
Hello

and when I using TLS to TLS between 
LINPHONE ---TLS--> FLEXISIP
FLEXISIP     ---TLS--> KAMAILIO

then I am not able to call and getting below error

> 380 flexisip : sips not allowed

Thanks

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
