### ISSUE TITLE
I installed flexisip but there is a problem in the configuration.?

### ISSUE THREAD

**Issue by sercangoger** [BelledonneCommunications/flexisip#141]
I installed flexisip on my cloud provider server. But I have a problem with the configuration settings.
When I want to make a call to my mobile application with android studio, I see that my request comes. but somehow the server does not make me register.
Looks like usersdb.txt cannot parse y.
Can you help with this?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
