### ISSUE TITLE
The following packages have unmet dependencies install problem ?

### ISSUE THREAD

**Issue by sercangoger** [BelledonneCommunications/flexisip#142]
I am getting this error while installing. What should I do?

"apt install bc-flexisip"
The following packages have unmet dependencies:
 bc-flexisip : Depends: libmbedcrypto1 (>= 2.8) but it is not installable
               Depends: libmbedtls10 (>= 2.0) but it is not installable
               Depends: libprotobuf10 but it is not installable
               Depends: libsnmp30 (>= 5.7.3+dfsg-1.8ubuntu3.6~dfsg) but it is not installablept install bc-flexisip

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
