### ISSUE TITLE
How to create fullchain.pem file.

### ISSUE THREAD

**Issue by sercan447** [BelledonneCommunications/flexisip#144]
I have two SSL files named **"certificate.crt and private.key".**
i these

With the help of the command
 **"openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem"**

I converted it to **"cert.pem and key.pem"** files.

flexisip is asking me for another file called **"fullchain.pem"**.
How can I create this **"fullchain.pem"** file. ?

**Comment by Viish** [comment]
Take a look at flexisip documentation on our wiki: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/TLS%20settings/

**Comment by stokito** [comment]
@Viish could you make a support of two certs files? So that users may just use fullchain.pem and privkey from LetsEncrypt directly.
