### ISSUE TITLE
flexisip tls version cipher problem

### ISSUE THREAD

**Issue by sercangoger** [BelledonneCommunications/flexisip#145]
I ran into a problem while configuring TLS for flexisip server.

The SSL I have, supports **TLSV1.3.**

but in the cipher settings in the flexisip.conf file, the following properties are available.

**#tls-ciphers=HIGH:!SSLv2:!SSLv3:!TLSv1:!EXP:!ADH:!RC4:!3DES:!aNULL:!eNULL**

When I look at my SSL information, I see that **TLSV1.2 and TLSV1.0** are not supported.
Could this be a problem for me?

**Comment by smititelu** [comment]
try setting this in config: tls-ciphers=HIGH:!SSLv2:!SSLv3:TLSv1.3:TLSv1.2:TLSv1:!EXP:!ADH:!RC4:!3DES:!aNULL:!eNULL

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
