### ISSUE TITLE
Required domain sip.domain.com or sips.domain.com ?

### ISSUE THREAD

**Issue by sercangoger** [BelledonneCommunications/flexisip#146]
I have a domain.
it is this way too.
www.mydomain.com
for me to communicate with TLS;
www.sip.domanim.com
or 
www.sips.domanim.com

Do I need to create a domain like.

is this a requirement?

**Comment by musti22160** [comment]
I have a similar issue. I had a domain like www.mydomain.net. And even though I made all the settings for FlexiSIP, I could not run TLS successfully.
I created a subdomain like example.mydomain.net. still no results.

Does it really need to be sip.mydomain.net or sips.mydomain.net?

**Comment by Failxxx** [comment]
Hello,
Here is the documentation to setup TLS with Flexisip: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/TLS%20settings/

Sincerely,
Félix.
