### ISSUE TITLE
how to configure flexisip to handle videoconferencing

### ISSUE THREAD

**Issue by luiz-telles** [BelledonneCommunications/flexisip#149]
Is there a specific parameter in the flexisip configuration for it to handle videoconferencing?

Is there any guide to configure and enable video conferencing?

**Comment by Failxxx** [comment]
Hello,

Here is the documentation to setup the conference server: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Conference%20server%20configuration/

Sincerely,
Félix.
