### ISSUE TITLE
ca not install via sudo yum install bc-flexisip on centos7

### ISSUE THREAD

**Issue by araby123** [BelledonneCommunications/flexisip#15]
there is now a problem with the flexisip are now If you install it via repo in new centos7 not working showing error and the installation not complete test it In Amzon EC2 & digital ocean 

Kindly any update about this issue

**Comment by ReisBenjamin** [comment]
What's the error you get ?

**Comment by araby123** [comment]
here after

`---> Package pyparsing.noarch 0:1.5.6-9.el7 will be installed
--> Running transaction check
---> Package bc-flexisip.x86_64 1:1.0.12-221.el7.centos will be installed
--> Processing Dependency: bc-hiredis-devel >= 0.11 for package: 1:bc-flexisip-1.0.12-221.el7.centos.x86_64
--> Processing Dependency: libhiredis.so.0.13()(64bit) for package: 1:bc-flexisip-1.0.12-221.el7.centos.x86_64
---> Package libsepol-devel.x86_64 0:2.5-6.el7 will be installed
---> Package pcre-devel.x86_64 0:8.32-17.el7 will be installed
--> Finished Dependency Resolution
Error: Package: 1:bc-flexisip-1.0.12-221.el7.centos.x86_64 (Belledonne)
           Requires: libhiredis.so.0.13()(64bit)
Error: Package: 1:bc-flexisip-1.0.12-221.el7.centos.x86_64 (Belledonne)
           Requires: bc-hiredis-devel >= 0.11
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest`



i do all as the book yum update &  install epel

**Comment by araby123** [comment]
any update ?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
