### ISSUE TITLE
I am unable to communicate with TLS.

### ISSUE THREAD

**Issue by sercangoger** [BelledonneCommunications/flexisip#151]
I can provide **UDP and TCP** communication with the l**inphone android** mobile application.
but I can't do **TLS** communication.
I have opened **issues** on this subject in linphone-android.
but i didn't get any good feedback on this **issue**.
We are sure that we have set **TLS config** properly.
If you look at the **issues** I mentioned below. You can better see what we are doing.

https://github.com/BelledonneCommunications/linphone-android/issues/1746

and

https://github.com/BelledonneCommunications/linphone-android/issues/1761

**Comment by musti22160** [comment]
We are having the same problem. We use Ngnix for proxy.
When we create any index.html, we can reach our server with SSL.
But when we try to do TLS with Flexisip, we get the same errors.
There is no problem with our UDP or TCP connection.
If anyone can really help with this, please help.

We have received all our certificates as both ssl and tlsv1 for a fee. We have uploaded it to both our server and our mobile application in accordance with all the instructions given.
But we can't figure out what we did wrong.
Apparently we don't have enough experience with the server.
Maybe we have a very simple configuration problem.

**Comment by Failxxx** [comment]
Hello,
Here is the documentation to setup TLS with Flexisip: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/TLS%20settings/

Sincerely,
Félix.
