### ISSUE TITLE
 403 Domain forbidden

### ISSUE THREAD

**Issue by avlubimov** [BelledonneCommunications/flexisip#152]
Can't allow call from external pbx to flexisip

 1 0.000000000   185.80.61.71 -> 185.80.61.72   SIP/SDP 1092 Request: INVITE sip:10@flexisip.example.com:5060 | 
 2 0.001730230   185.80.61.72 -> 185.80.61.71   SIP 453 Status: 403 Domain forbidden | 
 3 0.002510022   185.80.61.71 -> 185.80.61.72   SIP 392 Request: ACK sip:10@flexisip.example.com:5060 | 

[root@sip flexisip]# cat flexisip.conf 
[global]
aliases=localhost

[module::Registrar]
enabled=true
reg-domains=flexisip.example.com
db-implementation=internal

[module::Authentication]
enabled=true
auth-domains=flexisip.example.com
realm=flexisip.example.com
db-implementation=file
file-path=/etc/flexisip/users.db.txt

[module::DoSProtection]
enabled=false

[inter-domain-connections]
accept-domain-registrations=false

[module::Forward]
enabled=true
route=sip:asterisk.example.com:5080

[event-logs]
enabled=true
logger=filesystem
dir=/var/log/flexisip

Can i allow sip-calls from another sip-server to my flexisip users?

**Comment by Failxxx** [comment]
Hello,

Yes you can allow SIP calls from other SIP servers to your Flexisip users.
Here is the documentation for authentication: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Authentication/
Here is the documentation to make two SIP servers communicate together (whereas they do not manage the same SIP domain): https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Interoperability%20between%20two%20domains/

Sincerely,
Félix.
