### ISSUE TITLE
Different port at ACK and BYE

### ISSUE THREAD

**Issue by xyc0815** [BelledonneCommunications/flexisip#155]
Hello, I don't use flexisip for my SIP Service, but sometime I see calls coming from Linphone / flexisip. The invite, ringing and so on are okay, but when the ACK is expected, the message is blocked by the firewall. The problem is, that the ACK and also the BYE message where send from an unknown port and they are blocked.

Address in the SIP headers for my endpoint (public, source address) and the user endpoint (public, destination address)
source address: XXX.155.127.98
source port: 62175
destination address: XXX.230.158.49
destination port: 55588

ACK endpoints on the firewall client (public, source address) and my endpoint (public, destination address)
source address: XXX.230.158.49
source port: 30895
destination address: XXX.155.127.98
destination port: 62175

The expected port for the ACK call is 55588 on the client endpoint (public) but it comes from 30895. The new port is not known, because it was not send before in the invitation call. 
When I ignore the missing ACK I can open the RTP stream and it works, but for the BYE message it is the same problem. 
Is this a bug in flexisip or Linphone or what can I do to get these two messages thru the firwall?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
