### ISSUE TITLE
is flexisip a pbx?

### ISSUE THREAD

**Issue by jhjacobs81** [BelledonneCommunications/flexisip#159]
We're looking for a 3CX replacement and i ran into linphone. Next to that i saw flexisip which seems nice as well.
What i cant seem to figure out is how to configure flexisip as a pbx replacement so people can call a number, instead of a sip adress. I googled a bit and i see flexisip listed as a voip solution so it should be possible?

**Comment by Failxxx** [comment]
Hello,

Flexisip can indeed run as a back-to-back user agent allowing SIP-trunking (SIP-bridge).
Here is the documentation: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Back-to-back%20User%20Agent%20%28b2bua%29/

Sincerely,
Félix.
