### ISSUE TITLE
B2BUA configuration

### ISSUE THREAD

**Issue by HAKAOUI** [BelledonneCommunications/flexisip#166]
i tried to config flexisip to make a PSTN call if the user is note register, i have B2BUA work fine with my provider,  but the configuration of flexisip and routes.conf seems tricky ,couldn't configure properly . Do any one have proper configuration for flexisip for b2bua and the routs.conf ,If so kindly share :)

**Comment by CelluleInnovationFDI** [comment]
Any news

**Comment by Failxxx** [comment]
Hello,

Here is the documentation to configure Flexisip to setup SIP-trunking: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Back-to-back%20User%20Agent%20%28b2bua%29/SIP%20Bridge/

Sincerely,
Félix.
