### ISSUE TITLE
TLS connection fails on iOS

### ISSUE THREAD

**Issue by eskov-ea** [BelledonneCommunications/flexisip#168]
I have confugured flexisip and I decided to use TLS so in my config file I set 
        transports=sips:* sip:* 
        tls-cartificate-file=path/to/file
        tls-cartificate-private-key=path/to/key
        tls-cartificate-ca-file=path/to/ca/file

I also tried to specify ports for TLS/TCP connection, specify domen - result's the same.

The problem is when iOS device is connecting it does it infinite times despite the first connection is successful. 
In device log I can see it a thousand times per minute.
The server log shows it also. The log is drowned with these events.

On client side I use the login function as it described in the docs.

On Android it works perfectly between TLS and TCP.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
