### ISSUE TITLE
call drops after 32 seconds.

### ISSUE THREAD

**Issue by E2-Sterlin** [BelledonneCommunications/flexisip#169]
The call works good with audio at the both end, but it gets dropped after 32 seconds without hanging up by the users.
It happens for every call.
Any solution ?

Thanks in advance

**Comment by Hobby-Student** [comment]
In my experience this usually is a firewall problem. I had those problems (years ago) with an asterisk behind a pfSense with NAT. Perhaps replacing UDP with TCP could be your solution.

Info:
I have no experience with flexisip, but I saw your question while checking flexisip as a replacement for FreePBX.

**Comment by AlexAMCS** [comment]
Check the debug log and see if you're getting a SIP 504 from the server.

**Comment by E2-Sterlin** [comment]
> Check the debug log and see if you're getting a SIP 504 from the server.
Nope I am getting the 503 error

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
