### ISSUE TITLE
Help for flexisip subscribe user display in linphone android client

### ISSUE THREAD

**Issue by dipenpatel235** [BelledonneCommunications/flexisip#17]
Hello..
I am trying to finding how to display only my installed application user as per my server ?

How to show user presence in linphone android

I have server side setup done flexisip and kamailio.

But don't know how to show installed app contact and user presence.

I have did lots of search but not able to find proper solution.

So if you have some hint so please give me.

Thanks

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
