### ISSUE TITLE
flexisip-error-Could not create push notification: %sInvalid RFC8599 push parameters: pn-param declares 1 service(s), whereas there is/are 2 token(s) in pn-prid

### ISSUE THREAD

**Issue by devs-bg** [BelledonneCommunications/flexisip#170]
flexisip-error-Could not create push notification: %sInvalid RFC8599 push parameters: pn-param declares 1 service(s), whereas there is/are 2 token(s) in pn-prid

I have all setup the dev and prod certificates in /etc/flexisip/apn
But for some reason the flexisip return only pn-param=ABCD1234.com.app.com.voip instead of pn-param=ABCD1234.com.app.com.voip&remote

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
