### ISSUE TITLE
flexisip for one domain 

### ISSUE THREAD

**Issue by patel-cm** [BelledonneCommunications/flexisip#171]
hii , i've followed the wiki link for installing flexisip for one domain but still not able to connect to flexisip server form linphone client even after getting no error on starting it. can someone help with this issue please. 
my configuration file is as follow :

PROXY SETTINGS ##
[global]
transports=sips:192.168.1.38:5061 sip:127.0.0.1:5060;transport=tcp

[module::Authentication]
enabled=true
auth-domains=192.168.1.38
available-algorithms=SHA-256
trusted-hosts=127.0.0.1
db-implementation=soci
soci-backend=mysql
soci-connection-string=db='flexisip' user=flexisip password='*****' host='localhost'
soci-password-request=select password from accounts where where registerID= :id and domain= :domain;

[module::Registrar]
enabled=true
reg-domains=192.168.1.38
db-implementation=redis
redis-server-domain=localhost
redis-server-port=6379

max-expires=604800

[module::Router]

fork-late=true
message-delivery-timeout=604800

[module::PushNotification]

[presence-server]
enabled=true
transports=sip:127.0.0.1:5065;transport=tcp

[module::DoSProtection]
enabled=false

[module::Presence]
enabled=true
presence-server=sip:127.0.0.1:5065;transport=tcp

[conference-server]
enabled=true
transport=sip:127.0.0.1:6064;transport=tcp
conference-factory-uris=sip:conference-factory@192.168.1.38
outbound-proxy=sip:127.0.0.1:5060;transport=tcp
local-domains=192.168.1.38
database-backend=mysql
database-connection-string=db='flexisip' user=flexisip password='*****' host='localhost'

**Comment by ernesto-longwave** [comment]
There's a bug in the [module::Authentication] configuration, bad sql query:

change 
soci-password-request=select password from accounts where where registerID= :id and domain= :domain;

with
soci-password-request=select password from accounts where registerID= :id and domain= :domain;

Don't know if it will solve it for you, but you need to fix it

**Comment by amneiht** [comment]
I thing ,you has two problem
- first when using sips, you must specify your own certificate , if you dont have valid one using self-signed certificate and disable sever vertify in linphon config or using tcp conncet such as "sip:192.168.1.38"
Second you request is not right ,  according to <a href="https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/A.%20Configuration%20Reference%20Guide/2.3.2/module/Authentication"> here </a>
```
The request MUST returns a two-columns table, which columns are defined as follow:
 - 1st column: hashed password of the user or plain password if the associated algorithm is CLRTXT.
 - 2nd column: the algorithm used to hash the associated password. Supported values: 'CLRTXT', 'MD5', 'SHA-256'
 ```

example : " select password, 'MD5' from accounts where login = :id and domain = :domain"

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
