### ISSUE TITLE
NAT using public IP

### ISSUE THREAD

**Issue by E2-Sterlin** [BelledonneCommunications/flexisip#174]
Is it possible to configure flexisip behind NAT by using public IP without TLS certificate or domain Name?

**Comment by amneiht** [comment]
You can when you have static ip , you can connect to flexisp using sip tcp and public ip example sip:555@123.121.21.23 and . 
Specify your transport is "transport = sip:123.121.21.23;maddr=*"

**Comment by Failxxx** [comment]
Hello,

Here is the documentation to deploy Flexisip behind a NAT: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Deploying%20flexisip%20behind%20a%20NAT/

Sincerely,
Félix.
