### ISSUE TITLE
SIP TRUNK -- INVITE request

### ISSUE THREAD

**Issue by InnovMuch** [BelledonneCommunications/flexisip#175]
Hello, 
I am currently focused on implementing the SIP trunk. My goal is to redirect calls to a provider gateway, such as Vonage or SignalWire, in instances where the user doesn't answer a SIP call. For such scenarios, we're looking at having the call fall back to a PSTN provider and then rerouting it. Although I've set up the B2BUA module, the call isn't being forwarded to the provider when I use the sngrep command. Notably, I've observed that the proxy isn't sending any INVITE to the beb2ua gateway. Could you possibly assist with a suitable test configuration?

Best regards

**Comment by Failxxx** [comment]
Hello,

Here is the documentation to configure Flexisip (B2BUA, SIP-trunking): https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Back-to-back%20User%20Agent%20%28b2bua%29/SIP%20Bridge/
Please make sure to use module::B2bua in Flexisip proxy to forward requests to the B2BUA server: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/Back-to-back%20User%20Agent%20%28b2bua%29/SIP%20Bridge/

Sincerely,
Félix.
