### ISSUE TITLE
No Audio in NAT

### ISSUE THREAD

**Issue by E2-Sterlin** [BelledonneCommunications/flexisip#176]
Hi I have successfully configured asterisk with flexisip.
everything working good in private network.
But in Public network, there were no 2way audio.

Kindly help me regarding this.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
