### ISSUE TITLE
Building new Linphone with old ZRTP (not Quantum ZRTP)

### ISSUE THREAD

**Issue by mayjethva** [BelledonneCommunications/flexisip#177]
We are trying to update to the latest version of Linphone, but when building the app the Quantum ZRTP is being used by default.  The server we are using does not use the new ZRTP so we want to build with the old ZRTP on Linphone used.

Is there a method to change the ZRTP to the old method during the build of the application?  A setting or something else we can do to revert the ZRTP?  Currently any new build being made is not compatible with the other versions we are using.

**Comment by Failxxx** [comment]
Hello,

I understand that it is a problem when building the Linphone application. Please re-open a ticket on the appropriate repository (linphone-android or linphone-ios).

Sincerely,
Félix.
