### ISSUE TITLE
Calls not Working in Local Network when device is connected with Public IP.

### ISSUE THREAD

**Issue by E2-Sterlin** [BelledonneCommunications/flexisip#179]
Hi Everyone,
To handle background call , I tried to integrate Flexisip as frontend SIP Proxy server and Asterisk as backend SIP Register server.
It is working well by sending Voip notification.
Calls were working fine with 2 way audio in local network and public network in transport TCP.

But I am facing only two issues:
1.calls in Public network to Public network (i.e) both the device registered with Public IP and connected to public network (for example cellular network) is getting disconnected after 32 seconds when the transport is in UDP(especially in UDP Transport).

2.When the two devices registered with Public IP and connected to the Local network either in TCP or UDP transport and trying to call,
the call is not even getting connected, 
but it is working when it is connected to cellular network .

Kindly help me regarding this or share your thoughts which may helps me resolve the issue.

Thanks in Advance

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
