### ISSUE TITLE
Check whether event logging is functional

### ISSUE THREAD

**Issue by M-Stenzel** [BelledonneCommunications/flexisip#181]
Running version 2.3.3-7-gb335f4c0 of flexisip in a virtualized (OVH) Linux environment I face the problem that users cannot connect (Connection fails). Maybe there is sth. with certificates, some misconfiguration of the config file, need to check that...

I checked with several phones (latest linphone app), and the desktop app.

In order to tackle the problem I want to have some information from event logging, but the folder (/opt/belledonne-communications/log/flexisip/users/sip.instance...redacted for privacy reasons/) stays empty.

Now I wonder, does event logging fail or do the client users never reach the flexisip server? How can I troubleshoot the conversation between linphone clients and flexisip server?

This is the part of the config, where event logging is defined - so it is enabled, isn't it?

```
##
## Event logs contain per domain and user information about processed
## registrations, calls and messages.
## See: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Event%20logs%20and%20queries/
## for architecture and queries.
##
[event-logs]

# Enable event logs.
# Default: false
enabled=true

# Define logger for storing logs. It supports "filesystem", "database"
# and "flexiapi".
# Default: filesystem
logger=filesystem

# Directory where event logs are written as a filesystem (case when
# filesystem output is choosed).
# Default: /var/log/flexisip
filesystem-directory=/opt/belledonne-communications/log/flexisip
```

I can ping the server, the port (5061) is open. I do not receive any error messages in flexisip-presence.log , and flexisip-proxy.log. There does not seem to be a firewall issue here...

Martin.

**Comment by Failxxx** [comment]
Hello,

I guess that you are trying to debug your Flexisip deployment. You can find Flexisip logs in `/var/opt/belledonne-communications/log/flexisip/flexisip-proxy.log`. Please make sure to set global/log-level=debug in `flexisip.conf` to better understand what is going on.

Event logs are mainly designed for statistics collection: https://wiki.linphone.org/xwiki/wiki/public/view/FlexiAPI/

Sincerely,
Félix.
