### ISSUE TITLE
No 180 Ringing after 100 Trying in SIP Server

### ISSUE THREAD

**Issue by E2-Sterlin** [BelledonneCommunications/flexisip#182]
I have configured a SIP server where Flexisip is the frontend proxy server and Asterisk is the backend registrar server.
If I register my device with a Public IP or domain name in a local or private network, the call is not working.
getting SIP method like 100 trying during the call and no further 180 Ringing?

Kindly help me regarding this.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
