### ISSUE TITLE
Flexisip 24

### ISSUE THREAD

**Issue by harut420** [BelledonneCommunications/flexisip#189]
Hello
we find into your page advertised that end of May 2024 2.4 Flexisip was relaesed. https://www.linphone.org/news/release-flexisip-24-approaching

but i see stable is only c-flexisip-2.3.4-0.pre.47+7d82ea0b.el9.src.rpm

Do i miss something?
would be nice to understand more about your offereing as we are evaluationg to buy license.

Harut.

**Comment by Failxxx** [comment]
Hello,
You are right, the latest stable release is Flexisip 2.3.4.
Indeed, we have decided to make more efforts to release a stable version of Flexisip 2.3.X that is compatible with FirebaseV1 (for android push notifications). As a result, we have decided to postpone the release of Flexisip 2.4 until the end of August.

Félix.
