### ISSUE TITLE
Flexisip as proxy server video not working..

### ISSUE THREAD

**Issue by dipenpatel235** [BelledonneCommunications/flexisip#19]
Hello..
I have linphone client.
Flexisip is proxy server front end.
Kamailio is back end.

All audio calling is work fine but not working video calling.

Please help to fix it

Thanks

**Comment by E2-Sterlin** [comment]
@dipenpatel235 
Hi,
I am also trying the same.
Is it possible to share the configuration?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
