### ISSUE TITLE
b2bua cannot bridge to different protocol

### ISSUE THREAD

**Issue by skhrshin** [BelledonneCommunications/flexisip#191]
## Overview

b2bua cannot connect to another SIP server on protocol different than the one b2bua is listening on.

## Environment

Flexisip 2.3.4 on Debian GNU/Linux bookworm

## Steps to reproduce

1. Set up b2bua-server with `application=sip-bridge` and `transport=sip:127.0.0.1:6067;transport=udp`
2. Set up sip-bridge so that it would attempt to connect to some SIP server with `;transport=tcp`
3. Call from client connecting to the proxy so that b2bua would transfer to the SIP server on TCP.

## Expected behavior

b2bua can connect to the SIP server on TCP.

## Actual behavior

b2bua emits the following error and cannot connect to the destination.
```
belle-sip-error-No listening point matching for [tcp://<destination address>:<destination port>]
```

## Remarks

b2bua seems to be unable to connect with TCP when it is listening on UDP, and unable to connect with UDP when it is listening on TCP.

**Comment by ThibaultLemaire** [comment]
This is a known issue and has been fixed in b3400b65aea901522ec1bdeb44d1e186b95b4969 which will be part of the upcoming 2.4 release
