### ISSUE TITLE
Domain Registration configuration

### ISSUE THREAD

**Issue by musabsohail** [BelledonneCommunications/flexisip#2]
Hi,

I am trying to run my own flexisip server, it runs and get requests from browser but it starts with this error:

```
D: Loading domain registration configuration from /etc/flexisip/domain-registrations.conf
E: Cannot open domain registration configuration file '/etc/flexisip/domain-registrations.conf'
```

![1](https://cloud.githubusercontent.com/assets/5844239/12920545/da1a7cea-cf6a-11e5-857f-3037a395a093.png)
I am guessing because of this I am unable to register from my android client. Can someone kindly guide me, what am I doing wrong?
- Is my DB not connected?
- Or this domain-registrations.conf should have been created at the compile time?

Thank you,
Regards,
Musab.

**Comment by ReisBenjamin** [comment]
Hello,

This error should not impact client registration, problem's elsewhere.
What does the server answer when your client register ?
Did you edit flexisip.conf to match your client ?

Thanks

**Comment by ReisBenjamin** [comment]
Please reopen if issue still occurs
