### ISSUE TITLE
Linux release repositories are not accessible

### ISSUE THREAD

**Issue by Gorbas** [BelledonneCommunications/flexisip#205]
### Question

I tried to upgrade my Flexisip server in my Linux Server (Ubuntu 22.04.4 LTS), but I got a message that states that it cannot update from the given repository.

I have configured the repository in /etc/apt/sources.list.d/belledonne.list and I have even tried to include [allow-insecure=yes] in order to skip any security limitations:

```
# For Ubuntu 22.04 LTS
deb [arch=amd64][allow-insecure=yes] http://linphone.org/snapshots/ubuntu jammy beta
```

When I execute *apt update*

I get

```
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu jammy InRelease                                                                                                                      
Hit:3 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease                                                                                                              
Hit:4 https://deb.nodesource.com/node_22.x nodistro InRelease                                                                                                                     
Hit:5 https://repos.insights.digitalocean.com/apt/do-agent main InRelease                                                                                                    
Hit:6 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease                                                                          
Hit:7 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease                                                           
Hit:8 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease                                   
Ign:9 http://www.linphone.org/snapshots/ubuntu jammy InRelease
Err:10 http://www.linphone.org/snapshots/ubuntu jammy Release
  404  Not Found [IP: 2001:41d0:301::28 80]
Reading package lists... Done
E: The repository 'http://linphone.org/snapshots/ubuntu jammy Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I have double checked that I have used the correct configuration as it has been documented in https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/1.%20Installation/

**Comment by Failxxx** [comment]
Hello @Gorbas,
Thank you for your question.

We are indeed currently facing some issues with our servers.
It should be resolved soon.

Sincerely,
Félix.

**Comment by harut420** [comment]
Hello,
same here  : 

 yum info bc-flexisip
Belledonne-stable                                                                                                                                             24 kB/s |  83 kB     00:03
Errors during downloading metadata for repository 'Belledonne-stable':
  - Status code: 404 for http://www.linphone.org/snapshots/pub/rocky/9/stable/repodata/repomd.xml (IP: 51.91.236.193)
Error: Failed to download metadata for repo 'Belledonne-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Harut42

**Comment by Failxxx** [comment]
Hello,

Repositories are back.

Félix.
