### ISSUE TITLE
Different port on contact and invite

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/flexisip#24]
Hi @ReisBenjamin ..!!
Having problem with this:

when the push sends a register with a contact->
Contact: <sip:xxxxxxxxxx@170.51.93.62:18994

but the invite has a request uri->
INVITE sip:xxxxxxxxx@170.51.93.62:33254

When the push tells that the invite has to go to 18994 ,but it sending it to 33254 so the call dont establish

Can u help ?
Thanks!

**Comment by fedesenmartin** [comment]
@ReisBenjamin  any updates?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
