### ISSUE TITLE
Flexisip as a proxy re-register to backend server

### ISSUE THREAD

**Issue by kimvu3010** [BelledonneCommunications/flexisip#26]
Hi,
I am using Flexisip as a proxy for push notification and using FusionPBX as backend server and config it in module Forward. I have 2 problems here:
1. If I have 2 backend servers. How can I configure it in 1 Flexisip server?
2. In fusionPBX, every register session will expire in 3600s. After 3600s, my app can not use push notification anymore because when there is an inbound call, fusionpbx can not connect to flexisip anymore. Can I config Flexisip to re-register to backend server after a certain time?
Thank you.

**Comment by djkskqyr3** [comment]
I have same issue, did you fix?

**Comment by jsonsolanki** [comment]
Hello ,

We have also facing same issue. if anyone have resolve than kindly let me know.


Thanks.

**Comment by kimvu3010** [comment]
> Hello ,
> 
> We have also facing same issue. if anyone have resolve than kindly let me know.
> 
> Thanks.

Hello,
I ve been stop working on this for such a long time. Still, if anyone go through these issues:

Issue 1: If you have 2 fusionpbx backends, guess you can use HA proxy to load balance => I havent try this yet
Issue 2: In the end, we solve this by auto trigger re-register from sip client (some sip library support this method)

Best regard,
Kim.
