### ISSUE TITLE
flexisip regiyster in minor frequency than linphone to the backend

### ISSUE THREAD

**Issue by mako16** [BelledonneCommunications/flexisip#27]
hi there,

its posible that flexisip continue doing registrations even in a minor frequency than linphone uses.
now our linphone uses 604800 secs, but i would like flexisip to register to backend every 600 secs.
is this posible. can you help
thanks

**Comment by mako16** [comment]
hi any comments please?

**Comment by mako16** [comment]
@Gui13  any comments

**Comment by djkskqyr3** [comment]
@mako16 did you fix?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
