### ISSUE TITLE
domain-registrations.conf mentioned in main config does not exist.

### ISSUE THREAD

**Issue by AmineMansouriLondon** [BelledonneCommunications/flexisip#28]
After compiling with all necessary configurations, even with the minimal configuration, flexisip starts but with the error:
"Could not create outgoing transaction".
Which is directly affected by the domain-registrations.conf file which I had to create manually but the syntax is not mentioned anywhere in the docs or in the flexisip wiki. All that is mentioned is that this is a file holds information about the local domain name and SIP URI of the proxy which is very confusing without an example. I have researched for hours with no luck. Please assist with this issue, it is the final step to getting this running.

**Comment by zombiecong** [comment]
+1

**Comment by dipenpatel235** [comment]
+1

**Comment by willnaoosmit** [comment]
+1

i didn't found any example on the internet. Do you guys managed to do it?

**Comment by isikozsoy** [comment]
Hi! Did you solve this?

**Comment by Failxxx** [comment]
Hello,

I guess this link can help: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/A.%20Configuration%20Reference%20Guide/2.3.4/inter-domain-connections

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
