### ISSUE TITLE
Flexisip start error: pulseaudio can not connect

### ISSUE THREAD

**Issue by kimvu3010** [BelledonneCommunications/flexisip#29]
Hello,
I'm trying to install flexisip today and get this error. I searched for the key word but seem like nothing can help. Is there anyone can fix this error, please help.
Thanks a lot.
P/S: I've tried to install on both debian 9 and 8 but still get this error.

root@ip-172-31-7-240:/home/admin# service flexisip start
root@ip-172-31-7-240:/home/admin# /opt/belledonne-communications/bin/flexisip --show-experimental --dump-default all > /etc/flexisip/flexisip.conf
2018-03-02 06:59:01:966 mediastreamer-error-Connection to the pulseaudio server failed
root@ip-172-31-7-240:/home/admin# tail -f /var/opt/belledonne-communications/log/flexisip/FlexisipLogs_proxy.log 
2018-03-02 06:59:00:135 bctbx-error-[LAUNCHER] Watchdog PID: 423
**2018-03-02 06:59:00:140 mediastreamer-error-Connection to the pulseaudio server failed**
2018-03-02 06:59:00:169 flexisip-error-Cannot open domain registration configuration file '/etc/flexisip/domain-registrations.conf'

**Comment by SafeSoft-tlt** [comment]
Ни на что эти ошибки не влияют. Сейчас ещё появились ошибки сертификатов, они тоже не на что не влияют. Правда вы теперь не сможете правильно формировать ключи сертификата, потому-что получаете неверную информацию об ошибках. Вот как правильно формировать ключи полученные через cerbot для Flexisip:
#!/bin/sh
VAR1=`md5sum /etc/flexisip/tls/privkey.pem`
cp -f -L /etc/letsencrypt/live/site.com/privkey.pem /etc/flexisip/tls/privkey.pem
cp -f -L /etc/letsencrypt/live/site.com/cert.pem /etc/flexisip/tls/cert.pem
cp -f -L /etc/letsencrypt/live/site.com/fullchain.pem /etc/flexisip/tls/cafile.pem
cat /etc/flexisip/tls/privkey.pem /etc/flexisip/tls/cert.pem > /etc/flexisip/tls/agent.pem
VAR2=`md5sum /etc/flexisip/tls/privkey.pem`
if [ "$VAR1" != "$VAR2" ]; then
    service flexisip restart
fi

**Comment by SafeSoft-tlt** [comment]
Также работа сервера не протестирована с разными базами данных. Единственное на чём он работает это MySQL. Разработчики положились на сырой проект SOCI, упростили себе жизнь и сделали всем остальным много проблем.

**Comment by kimvu3010** [comment]
You say the error not affect, yet i found myself can not run most of the cmd for flexisip. For example this cmd:
/opt/belledonne-communications/bin/flexisip --show-experimental --dump-default all > /etc/flexisip/flexisip.conf

And its show this error: 2019-01-18 07:07:44:937 mediastreamer-error-Connection to the pulseaudio server failed

I still stuck with this until now, anyone can fix it please.

**Comment by bunphotk** [comment]
Seems you are trying to run 'flexisip start' by root while the flexisip has been installed by a user 'e.g. admin' or vice versa. Try 
export PATH=$PATH:/etc/flexisip/  from user login who installed flexisip then root can run the cmd.
You may also need export /opt/belledonne-communication/bin/  too.

**Comment by harut420** [comment]
Dear all, 
amyone got success to use tls-verify-incoming=1 with Flexisip and liphone ?
i m getting 
flexisip-debug-tls_connect(0x5591221910f0): TLS setup failed (error:00000001:lib(0):func(0):reason(1))
 actually i did not setted up into liphone 
client_cert_chain=/pathTo/newcert.pem
client_cert_key=/pathTo/clientkey.pem

I would try that and post feedback.
would be very apprechated any suggestion

**Comment by harut420** [comment]
I solved adding into linphone conf file path as described above

**Comment by Anurag0987** [comment]
> I solved adding into linphone conf file path as described above

Hi, I am facing similar error "flexisip-debug-tls_connect(0x5580eafdbf30): TLS setup failed (error:00000001:lib(0):func(0):reason(1))"
can you pleas be more specific on how did you solve the error.
Thank you.

**Comment by sercan447** [comment]
flexisip-debug-tls_connect(0x5654a9a29970): TLS setup failed (error:00000001:lib(0):func(0):reason(1))

i was getting the same error.

export PATH=$PATH:/etc/flexisip/

I added path but the problem is not solved.

**Comment by sercan447** [comment]
**client_cert_chain=/pathTo/newcert.pem
client_cert_key=/pathTo/clientkey.pem**

In which file should I add the above code? i these codes
**/etc/flexisip/flexisip.conf**

I added it to the file.
but there was no change.

in this way;
**client_cert_chain=/etc/letsencrypt/live/domain.com/cert.pem
client_cert_key=/etc/letsencrypt/live/domain.com/privkey.pem**

I also defined it as a module and tried it this way.

**[sip]
client_cert_chain=/etc/letsencrypt/live/shnbilisim.com/cert.pem
client_cert_key=/etc/letsencrypt/live/shnbilisim.com/privkey.pem**

make these experiments

**systemctl restart flexisip-proxy
systemctl restart flexisip-presence**

I got an error when I restarted the services.

What exactly is wrong?
Can you help with this.?
