### ISSUE TITLE
installing flexisip

### ISSUE THREAD

**Issue by TitiGil** [BelledonneCommunications/flexisip#30]
hello every body. I've just tried to install flexisip, but in middle of way i got this error 

**************************
Scanning dependencies of target EP_sofiasip
make[2]: Leaving directory '/root/new/flexisip/WORK/flexisip/cmake'
make[2]: Entering directory '/root/new/flexisip/WORK/flexisip/cmake'
[ 68%] Creating directories for 'EP_sofiasip'
[ 70%] No download step for 'EP_sofiasip'
[ 72%] No patch step for 'EP_sofiasip'
[ 74%] No update step for 'EP_sofiasip'
[ 75%] Performing configure step for 'EP_sofiasip'
/root/new/flexisip/WORK/flexisip/cmake/EP_sofiasip_configure.sh: 40: /root/new/flexisip/WORK/flexisip/cmake/EP_sofiasip_configure.sh: /root/new/flexisip/submodules/externals/sofia-sip/autogen.sh: not found
/root/new/flexisip/WORK/flexisip/cmake/EP_sofiasip_configure.sh: 41: /root/new/flexisip/WORK/flexisip/cmake/EP_sofiasip_configure.sh: /root/new/flexisip/submodules/externals/sofia-sip/configure: not found
CMakeFiles/EP_sofiasip.dir/build.make:106: recipe for target '/root/new/flexisip/WORK/flexisip/Stamp/EP_sofiasip/EP_sofiasip-configure' failed
make[2]: *** [/root/new/flexisip/WORK/flexisip/Stamp/EP_sofiasip/EP_sofiasip-configure] Error 127
make[2]: Leaving directory '/root/new/flexisip/WORK/flexisip/cmake'
CMakeFiles/Makefile2:259: recipe for target 'CMakeFiles/EP_sofiasip.dir/all' failed
make[1]: *** [CMakeFiles/EP_sofiasip.dir/all] Error 2
make[1]: Leaving directory '/root/new/flexisip/WORK/flexisip/cmake'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/root/new/flexisip/WORK/flexisip/cmake'
*****************

thanks for any idea help me????!!!

**Comment by TheNazzi89** [comment]
I know it’s an old issue. But I'm facing it right now. Did you remember how you resolved this?
