### ISSUE TITLE
Runnig Flexisip

### ISSUE THREAD

**Issue by TitiGil** [BelledonneCommunications/flexisip#31]
hello everybody 
when i run flexisip i got this error 

> flexisip: symbol lookup error: /usr/lib/libflexisip.so: undefined symbol: tptag_tls_ciphers

thank for any idea!

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
