### ISSUE TITLE
Error in the latest build of aptitude bc-flexisip

### ISSUE THREAD

**Issue by SafeSoft-tlt** [BelledonneCommunications/flexisip#32]
When you send a message in the chat after the flexisip-debug-PushNotificationClient call, an error is generated:
bctbx-error-Flexisip apparently crashed, respawning now...

During voice calls, there is no error.
How do I return an old version of bc-flexisip?

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
