### ISSUE TITLE
Compile error, cannot find source file buf.c

### ISSUE THREAD

**Issue by aeetos** [BelledonneCommunications/flexisip#37]
I am attempting a clean compile on ubuntu with a lot of options enabled, specifically:

`./prepare.py -c ; ./prepare.py -DENABLE_PROTOBUF=ON -DENABLE_QRCODE=ON -DENABLE_VIDEO=ON -DENABLE_TRANSCODER=ON -DENABLE_CONFERENCE=ON -DENABLE_FFMPEG=ON -DENABLE_SOCI=ON -DENABLE_JPEG=ON -DENABLE_SRTP=ON -DENABLE_MPEG4=ON -DENABLE_PRESENCE=ON -DENABLE_PROTOBUF=ON -DENABLE_OPENH264=ON -DENABLE_NON_FREE_CODECS=ON -DENABLE_LIME_X3DH=ON -DENABLE_WEBRTC_AECM=ON -DENABLE_WEBRTC_AEC=ON -DENABLE_PRESENCE=ON -DENABLE_VCARD=ON -DENABLE_LIME=ON -DENABLE_G729=ON -DENABLE_V4L=ON -DENABLE_ZRTP=ON -DENABLE_OPUS=ON`

Things go smoothly until EP_xml2 when I get an error about an unknown buf.c file. 

When I remove the include from CMakeLists.txt the compile continues past the error, but of course I have no idea if that's the best solution.

This is with commit c23a39bc0f92362489e7fb37517bd8f8400a58d7

Details:

```
Cloning into 'EP_xml2'...
Note: checking out 'v2.8.0'.
<< snip >>

HEAD is now at c943f70... Release of libxml2-2.8.0
[ 27%] Performing patch step for 'EP_xml2'
[ 27%] Performing update step for 'EP_xml2'
[ 28%] Performing configure step for 'EP_xml2'

<< snip >>

CMake Error at CMakeLists.txt:351 (add_library):
  Cannot find source file:

    buf.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Generating done
-- Build files have been written to: /root/build/flexisip_clean/WORK/flexisip/Build/xml2
CMakeFiles/EP_xml2.dir/build.make:107: recipe for target '/root/build/flexisip_clean/WORK/flexisip/Stamp/EP_xml2/EP_xml2-configure' failed
make[3]: *** [/root/build/flexisip_clean/WORK/flexisip/Stamp/EP_xml2/EP_xml2-configure] Error 1
make[3]: Leaving directory '/root/build/flexisip_clean/WORK/flexisip/cmake'
CMakeFiles/Makefile2:1280: recipe for target 'CMakeFiles/EP_xml2.dir/all' failed
make[2]: *** [CMakeFiles/EP_xml2.dir/all] Error 2
make[2]: Leaving directory '/root/build/flexisip_clean/WORK/flexisip/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/build/flexisip_clean/WORK/flexisip/cmake'
Makefile:14: recipe for target 'flexisip-build' failed
make: *** [flexisip-build] Error 2
```

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
