### ISSUE TITLE
Failed to clone repository for zxing-cpp

### ISSUE THREAD

**Issue by aeetos** [BelledonneCommunications/flexisip#38]
I am attempting a clean compile on ubuntu with a lot of options enabled, specifically:

`./prepare.py -c ; ./prepare.py -DENABLE_PROTOBUF=ON -DENABLE_QRCODE=ON -DENABLE_VIDEO=ON -DENABLE_TRANSCODER=ON -DENABLE_CONFERENCE=ON -DENABLE_FFMPEG=ON -DENABLE_SOCI=ON -DENABLE_JPEG=ON -DENABLE_SRTP=ON -DENABLE_MPEG4=ON -DENABLE_PRESENCE=ON -DENABLE_PROTOBUF=ON -DENABLE_OPENH264=ON -DENABLE_NON_FREE_CODECS=ON -DENABLE_LIME_X3DH=ON -DENABLE_WEBRTC_AECM=ON -DENABLE_WEBRTC_AEC=ON -DENABLE_PRESENCE=ON -DENABLE_VCARD=ON -DENABLE_LIME=ON -DENABLE_G729=ON -DENABLE_V4L=ON -DENABLE_ZRTP=ON -DENABLE_OPUS=ON`

This is with commit c23a39b

I get an error when it tries to clone the repo for EP_zxing

```
CMake Error at /root/build/flexisip_clean/WORK/flexisip/tmp/EP_zxing/EP_zxing-gitclone.cmake:40 (message):
  Failed to clone repository: 'git@github.com:glassechidna/zxing-cpp.git'

CMakeFiles/EP_zxing.dir/build.make:89: recipe for target '/root/build/flexisip_clean/WORK/flexisip/Stamp/EP_zxing/EP_zxing-download' failed
make[3]: *** [/root/build/flexisip_clean/WORK/flexisip/Stamp/EP_zxing/EP_zxing-download] Error 1
make[3]: Leaving directory '/root/build/flexisip_clean/WORK/flexisip/cmake'
CMakeFiles/Makefile2:1082: recipe for target 'CMakeFiles/EP_zxing.dir/all' failed
make[2]: *** [CMakeFiles/EP_zxing.dir/all] Error 2
make[2]: Leaving directory '/root/build/flexisip_clean/WORK/flexisip/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/build/flexisip_clean/WORK/flexisip/cmake'
Makefile:14: recipe for target 'flexisip-build' failed
make: *** [flexisip-build] Error 2
```

I fixed this by changing line 29 of the EP_zxing-gitclone.cmake file from this:
`COMMAND "/usr/bin/git" clone --origin "origin" "git@github.com:glassechidna/zxing-cpp.git" "EP_zxing"`
to this
`COMMAND "/usr/bin/git" clone --origin "origin" "https://github.com/glassechidna/zxing-cpp.git" "EP_zxing"`

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
