### ISSUE TITLE
build flexisip failed on Centos 7

### ISSUE THREAD

**Issue by CaseyGuanSun** [BelledonneCommunications/flexisip#42]
it print this error :/flexisip/submodules/externals/hiredis" does not appear to contain CMakeLists.txt.
when I build flexisip on Centos 7

**Comment by syco** [comment]
I'm sorry if I'm out of scope, but the only way I got flexisip working is by using the provided repository:
[https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Installation/#HInstallationonCentos7](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Installation/#HInstallationonCentos7)

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
