### ISSUE TITLE
This problem has been bothering me for a week

### ISSUE THREAD

**Issue by HelloCpp3032** [BelledonneCommunications/flexisip#44]
I have deployed flexisip on my server, an linphone can talk or video with each other only in the same network and it must turn on ICE. If not, linphone only can make peer ring the bell without any video or voice. I searched for github and Google, but didn't find any related questions. Was it because I deployed flexisip which step was wrong.

**Comment by amneiht** [comment]
do you enabed module MediaRelay

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
