### ISSUE TITLE
sofia-sip ARM runtime segmentation fault

### ISSUE THREAD

**Issue by marksaitis** [BelledonneCommunications/flexisip#47]
Hi,

---Compiled on Ubuntu Bionic 10/2018 ARM 64bit with clang.
---Error: Segmentation fault.
Any ideas?

----GDB below----
(gdb) where
#0  0x0000007fb77128a8 in tl_gets (lst=<optimized out>, tag=<optimized out>, value=<optimized out>)
    at su_taglist.c:412
(gdb) list 400,430
400
401       for (t = ta_args(ta); t; t = (tagi_t *)t_next(t)) {
402         tag_type_t tt = t->t_tag;
403
404         if (!tt)
405           continue;
406
407         if (tt->tt_class == ref_tag_class) {
408           assert(((tag_type_t)tt->tt_magic)->tt_class->tc_ref_set);
409           n += tl_get(tt, (void *)t->t_value, lst);
410         }
411     #if !defined(NDEBUG)
412         else if (tt->tt_class && tt->tt_class->tc_ref_set) {
413           fprintf(stderr, "WARNING: tag %s::%s directly used by tl_gets()\n",
414                   tt->tt_ns ? tt->tt_ns : "", tt->tt_name ? tt->tt_name : "");
415           assert(tt->tt_class == ref_tag_class);
416         }
417     #endif
418       }
419
420       ta_end(ta);
421
422       return n;
423     }
424
425     /** Find tags from given list.
426      *
427      * Copies values of argument tag list into the reference tags in the tag
428      * list @a lst.
429      *
430      * @sa tl_gets()
(gdb) print tt
$5 = (tag_type_t) 0x7fb7e5123e
(gdb) print tt_class
No symbol "tt_class" in current context.
(gdb) print tt->tt_class
$6 = (tag_class_t *) 0x78656c4600736e69
(gdb) print tt->tt_class->tc_ref_set
Cannot access memory at address 0x78656c4600736eb9

-----END OF GDB----

**Comment by smorlat** [comment]
Hi,

Could you please indicate the full backtrace, and describe a bit your build procedure ?

Best regards,

Simon

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
