### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by looserouting** [BelledonneCommunications/flexisip#48]
i want to buid flexisip with the following options:

 ./prepare.py flexisip -DENABLE_PRESENCE=OFF -DENABLE_CONFERENCE=OFF -DENABLE_SRTP=ON -DENABLE_OPUS=ON -DENABLE_SOCI=OFF -DENABLE_REDIS=OFF -DENABLE_ISAC=ON -DENABLE_TRANSCODER=ON -DENABLE_SOUND=NO

1st issue
ENABLE_SOUND=NO doesn't work and will be ignored
after failing I added it manuelly in 
/usr/local/src/flexisip/WORK/flexisip/cmake/CMakeFiles/EP_ms2.dir/build.make

2nd issue
can't use ENABLE_SOCI=OFF
there is a dependency

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
