### ISSUE TITLE
binaries from Debian repo not starting: libflexisip.so: undefined symbol

### ISSUE THREAD

**Issue by alpha197** [BelledonneCommunications/flexisip#52]
I tried to install the flexisip binaries under Debian 9 following [the official guide](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Installation/#HInstallationonDebian9Stretch28worksforDebian8Jessietoo29).

It seems that something in the precompiled package is broken. Start of bc-flexisip binary fails with this error:

> root@lxc-dmz-sipproxy:~# /opt/belledonne-communications/bin/flexisip --dump-default all > /etc/flexisip/flexisip.conf
/opt/belledonne-communications/bin/flexisip: symbol lookup error: /opt/belledonne-communications/lib/libflexisip.so: undefined symbol: _ZN8linphone8ChatRoom21setParticipantDevicesERKSt10shared_ptrIKNS_7AddressEERKNSt7__cxx114listIS1_IS2_ESaIS9_EEE

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
