### ISSUE TITLE
Store and Forward issue with short reg_expires

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/flexisip#55]
I am using Flexisip and Linphone with TLS authentication and reg_expires=60 (instead of push). SIP messages sent form A to B are stored on the server only if:

1. Linphone app of B is closed (UNREGISTRATION)
or
2. Mobile was switched off (which results in proper UNREGISTRATION)

But if B loose the network for more than 60s (having mobile on and Linphone up), then A cannot send any message to B.

Is there any way to configure Flexisip (or Linphone), so that it could Store SIP messages in all cases, even when B loose his network (=REGISTER is not sent on time) ? Or is it a bug ?

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
