### ISSUE TITLE
How to uninstall flexisip?

### ISSUE THREAD

**Issue by wlfbitfc123** [BelledonneCommunications/flexisip#57]
I have install flexisip successfully.Now I want to do some optional change and recompiled source code and reinstall flexisip.But it seems that new flexisip don't override the old one.How can I uninstall flexisip first?
Thanks.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
