### ISSUE TITLE
Error in Compilation with soci

### ISSUE THREAD

**Issue by shdaro** [BelledonneCommunications/flexisip#58]
I was installing flexisip with the this [instruction](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Installation/#HInstallationfromsourcesusinggit) 

git clone git://git.linphone.org/flexisip --depth 1 --recursive
cd flexisip
./prepare.py flexisip
 make -C WORK/flexisip/cmake

When I run `make -C WORK/flexisip/cmake` I found the following errors.

Your help will be appreciated. Thanks

=========================================================== 

-- Found Threads: TRUE  
-- Config dir: /home/support/flexisip/OUTPUT/etc/flexisip
-- Found SofiaSipUa: /home/support/flexisip/OUTPUT/include/sofia-sip-1.13 (found suitable version "1.13.33bc", minimum required is "1.13.11") 
-- Found XercesC: /home/support/flexisip/OUTPUT/lib/libxerces-c.so (found version "3.1.4") 
-- Found LibXsd: /home/support/flexisip/OUTPUT/include;/home/support/flexisip/OUTPUT/include  
-- Looking for arc4random
-- Looking for arc4random - not found
-- GCC version 4.8.5 should have steady_clock
-- Looking for redisAsyncCommand
-- Looking for redisAsyncCommand - found
-- Found Hiredis: /home/support/flexisip/OUTPUT/include  
-- Soci found: Looking for plugins
--     * Plugin mysql not found.
--     * Plugin odbc not found.
--     * Plugin postgresql not found.
--     * Plugin sqlite3 found /home/support/flexisip/OUTPUT/lib/libsoci_sqlite3.so.
CMake Error at cmake/FindSoci.cmake:87 (MESSAGE):
  Required component mysql not found.  It seems that Soci was built without
  support of mysql, consider rebuilding it.
Call Stack (most recent call first):
  CMakeLists.txt:211 (find_package)

-- Found Soci: /home/support/flexisip/OUTPUT/include/soci  
-- MSGPACK not found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.0.1f", minimum required is "0.9.8") 
-- 
-- The following OPTIONAL packages have been found:

 * Threads
 * XercesC
 * LibXsd
 * PkgConfig

-- The following REQUIRED packages have been found:

 * SofiaSipUa (required version >= 1.13.11)
 * ORTP (required version >= 0.21)
 * BcToolbox (required version >= 0.0.3)
 * Belr
 * Hiredis
 * Mediastreamer2
 * BelleSIP
 * Linphone
 * LinphoneCxx
 * Soci
 * OpenSSL (required version >= 0.9.8)

-- Found Git: /usr/bin/git (found version "1.9.1") 
-- Flexisip LIBS : bctoolbox;belr;-lpthread;linphone++;ortp;/home/support/flexisip/OUTPUT/lib/libsofia-sip-ua.so;/home/support/flexisip/OUTPUT/lib/libxerces-c.so;/home/support/flexisip/OUTPUT/lib/libhiredis.so;bellesip;bellesip;linphone;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/home/support/flexisip/OUTPUT/lib/libsoci_core.so
-- Flexisip INCLUDES : /home/support/flexisip/include/flexisip;/home/support/flexisip/OUTPUT/include;/home/support/flexisip/OUTPUT/include;/home/support/flexisip/OUTPUT/include;/home/support/flexisip/OUTPUT/include;/home/support/flexisip/src/xml;/home/support/flexisip/OUTPUT/include;/home/support/flexisip/OUTPUT/include;presence;/home/support/flexisip/OUTPUT/include;/home/support/flexisip/OUTPUT/include;/usr/include;/home/support/flexisip/OUTPUT/include/libxml2;/usr/include;/home/support/flexisip/OUTPUT/include/soci;SOCI_MYSQL_INCLUDES-NOTFOUND
-- Flexisip DEPENDENCIES : 
-- Startup scripts configured with bindir=/home/support/flexisip/OUTPUT/bin
-- Found Git: /usr/bin/git (found suitable version "1.9.1", minimum required is "1.7.1") 
-- Package file name is flexisip-presence-1.0.13-165
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/support/flexisip/src/SOCI_MYSQL_INCLUDES
   used as include directory in directory /home/support/flexisip/src

-- Configuring incomplete, errors occurred!
See also "/home/support/flexisip/WORK/flexisip/Build/flexisip/CMakeFiles/CMakeOutput.log".
See also "/home/support/flexisip/WORK/flexisip/Build/flexisip/CMakeFiles/CMakeError.log".
make[2]: *** [/home/support/flexisip/WORK/flexisip/Stamp/EP_flexisip/EP_flexisip-configure] Error 1
make[2]: Leaving directory `/home/support/flexisip/WORK/flexisip/cmake'
make[1]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
make[1]: Leaving directory `/home/support/flexisip/WORK/flexisip/cmake'
make: *** [all] Error 2
make: Leaving directory `/home/support/flexisip/WORK/flexisip/cmake'

**Comment by TestWts2017** [comment]
I am facing same issue, any updates on this?

**Comment by edhelas** [comment]
Hi, I just encountered this issue on my Debian as well.
You need to install `libmysqlclient-dev` and `libsoci-dev` to install the missing files on your system and compile the soci part correctly.

**Comment by avalanche15** [comment]
> Hi, I just encountered this issue on my Debian as well. You need to install `libmysqlclient-dev` and `libsoci-dev` to install the missing files on your system and compile the soci part correctly.

THX MY FRIEND!
