### ISSUE TITLE
Receives INVITE, sends push notification and then doesn't wait for linphone to connect

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/flexisip#59]
I've got a flexisip installation here proxying an Asterisk instance with a Linphone feature/release-4.1 client enabled for push.

If I make a call to the linphone client after it registers to the proxy and is still running on the phone everything works fine.

However if I terminate the linphone client (recall, enabled for push, so this should work fine), when flexisip receives the INVITE from Asterisk to forward to linphone, it sends a push notification to the firebase server and then immediately tries to send an INVITE to linphone.  That INVITE is of course refused because linphone has not had enough time to start and REGISTER in response to the push, but flexisip then immediately responds to asterisk with a 503 response.

Shouldn't there be some waiting and retrying going on here to allow linphone to be woken and REGISTER rather than immediately sending a 503 to the PBX?

Here's the [flexisip log](http://brian.interlinx.bc.ca/flexisip-503.txt).

**Comment by brianjmurrell** [comment]
Any thoughts on this?

I can't see how flexisip, as a push proxy is at all usable given the way it handles the above scenario.

I'd just like to know if I should give up on flexisip and roll my own solution.

**Comment by SafeSoft-tlt** [comment]
Install: aptitude install bc-flexisip = 1.0.13-198
(it may be a bit earlier or later versions). Most new versions with Push stopped working altogether.

**Comment by SafeSoft-tlt** [comment]
And better write your notification module:
https://community.asterisk.org/t/interest-in-implementing-sip-push-notification/75563/17

Just do not bypass the restrictions of 255 characters as written in the example. Better change the size of the table field in the Asterisk database.

**Comment by driesken** [comment]
@brianjmurrell 
Mind sharing your flexisip.conf? Are you using PJSIP? I'm having issues with authentication and was wondering if you were able to use MD5 auth?

**Comment by SafeSoft-tlt** [comment]
# encode string as "username:domain:password" 

ROR
self.ha1 = Digest::MD5.hexdigest("#{self.sip_username}:#{domain}:#{self.password}")

PHP
$ha1 = md5("$sip_username:$domain:$password")

**Comment by driesken** [comment]
Yes, I'm aware on how to generate the MD5 (all my endpoints are using md5 for auth), but I don't think the MD5 is being interpreted correctly by flexisip (I'm using the userdb.conf).
For some reason, it can't parse the realm and takes the IP-address of the Asterisk node by default.

**Comment by SafeSoft-tlt** [comment]
I use postgresql. Domain Linphone takes from account settings.

**Comment by driesken** [comment]
> I use postgresql. Domain Linphone takes from account settings.

Interesting. Could try that instread of the flat text file.
Are you connecting by ODBC? Which parameters are you using?
I'm having some trouble because of an unknown "request" parameter (latest snapshot):
`2019-07-01 13:43:14:513 flexisip-error-Unsupported parameter 'request' in section [module::Authentication] at line 124. Did you mean 'count-eval-true'?`

**Comment by SafeSoft-tlt** [comment]
ODBC is not supported in my version of Flexisip. I use SOCI.

**Comment by brianjmurrell** [comment]
@driesken I don't have anything near a working flexisip configuration.  I've actually given up on trying to get flexisip working as frankly, I find the documentation and examples of how to configure flexisip very lacking.  They were written by somebody obviously very familiar with flexisip for people who are also familiar with flexisip, IMHO.

If any of you have working flexisip configurations, **I** would actually appreciate seeing a working configuration.  I'm specifically looking for flexisip to be a proxy for Asterisk to linphone phones with push notification.

**Comment by driesken** [comment]
@brianjmurrell 
I couldn't agree more. After struggling with flexisip.conf I've finally managed to get some basics working.
[flexisip.txt](https://github.com/BelledonneCommunications/flexisip/files/3349877/flexisip.txt) 

I must say that I couldn't get the flexisip authentication module working. When I did some testing, I first tried the db-implementation "file". Afterwards, I tried soci as @SafeSoft-tlt suggested but that fails somewhere in the authentication process. The module does notice whether the MD5 is succesfull/wrong but the logs won't indicate what's going wrong afterwards.

I'm not sure though whether this component fits well into Asterisk. A dial within Asterisk to the contact (Linphone is closed but the contact is still present within Asterisk) immediately returns CONGESTION, so there is no time for the device to wake up. I'm also having issues with one-way audio, untill the call is paused (so a re-INVITE) is sent.

For me flexisip has some great potential but at the moment I won't consider running it in a production environment. I'm doing push within Asterisk and so far this works pretty good. The only problem (and that's where Flexisip comes in) is that Flexisip should be able to resend the INVITE untill the device has sucessfully woken.

**Comment by brianjmurrell** [comment]
> I must say that I couldn't get the flexisip authentication module working

Is your configuration (just skimmed it) (only) intended to proxy Asterisk for linphone clients so that flexisip will send push notifications to linphone clients when their extension is dialed on Asterisk?

If yes, then why do you want/need flexisip to authenticate clients?  IMHO, it should just be passing that authentication through to Asterisk.  IOW, flexisip shouldn't have any kind of client account database at all and just defer authentication of those client to Asterisk.

**Comment by driesken** [comment]
> > I must say that I couldn't get the flexisip authentication module working
> 
> Is your configuration (just skimmed it) (only) intended to proxy Asterisk for linphone clients so that flexisip will send push notifications to linphone clients when their extension is dialed on Asterisk?
> 
> If yes, then why do you want/need flexisip to authenticate clients? IMHO, it should just be passing that authentication through to Asterisk. IOW, flexisip shouldn't have any kind of client account database at all and just defer authentication of those client to Asterisk.

That's correct, proxy only. Yes you're right! I only tried it because maybe it would be required for Flexisip to keep track of its push tokens along with each extension.

**Comment by SafeSoft-tlt** [comment]
Install: aptitude install bc-flexisip = 1.0.13-198
[flexisip.txt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt)

**Comment by driesken** [comment]
> Install: aptitude install bc-flexisip = 1.0.13-198
> [flexisip.txt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt)

You don't have push enabled in your config?

**Comment by SafeSoft-tlt** [comment]
If you turn it on you will need to configure the field:
firebase-projects-api-keys =
and indicate where your Apple VoIP certificate is in the field:
apple-certificate-dir =

To do this, you will need to collect your version of Linphone for Android and iPhone.

**Comment by driesken** [comment]
> If you turn it on you will need to configure the field:
> firebase-projects-api-keys =
> and indicate where your Apple VoIP certificate is in the field:
> apple-certificate-dir =
> 
> To do this, you will need to collect your version of Linphone for Android and iPhone.

I've configured the "firebase-projects-api-keys" but the push isn't requested. It works fine within Asterisk and with the flexisip_pusher though.

**Comment by SafeSoft-tlt** [comment]
Because in Flexisip there is an error in the latest versions. Module [module :: PushNotification] is disabled!

**Comment by SafeSoft-tlt** [comment]
You also need to run the application with the configured account, otherwise Flexisip will not find a device for push notifications. To prevent device information from being lost when rebooting Flexisip, install Redis.

**Comment by brianjmurrell** [comment]
> @brianjmurrell
> I've finally managed to get some basics working.
> [flexisip.txt](https://github.com/BelledonneCommunications/flexisip/files/3349877/flexisip.txt)

In your config, you have:

```
transports=sip:*
```

Does that mean that you have flexisip and Asterisk on different machines?

**Comment by driesken** [comment]
> > @brianjmurrell
> > I've finally managed to get some basics working.
> > [flexisip.txt](https://github.com/BelledonneCommunications/flexisip/files/3349877/flexisip.txt)
> 
> In your config, you have:
> 
> ```
> transports=sip:*
> ```
> 
> Does that mean that you have flexisip and Asterisk on different machines?

Yes I have.

**Comment by brianjmurrell** [comment]
> Yes I have.

So that's different for me.  I have them on the same machine with flexisip listening on port 5061.

Do you even get successful linphone registrations at all?  The account status for me on linphone stays yellow, indicating that the registration does not complete, which is probably indicative of the fact that my Asterisk gets absolutely nothing from flexisip while linphone is apparently trying to register to flexisip.

I'd expect to see a parallel registration from flexisip to Asterisk while linphone is trying to register to flexisip.

**Comment by driesken** [comment]
> > Yes I have.
> 
> So that's different for me. I have them on the same machine with flexisip listening on port 5061.
> 
> Do you even get successful linphone registrations at all? The account status for me on linphone stays yellow, indicating that the registration does not complete, which is probably indicative of the fact that my Asterisk gets absolutely nothing from flexisip while linphone is apparently trying to register to flexisip.
> 
> I'd expect to see a parallel registration from flexisip to Asterisk while linphone is trying to register to flexisip.

Yes, registration works fine. When you execute "pjsip set logger on" (or do a tcpdump), do you see registrations coming in which get an "Unauthorized" from Asterisk? I've had some issues with a wrong realm being used but that was fixed by using "reg_identity" in my linphone xml provisioning files.

**Comment by brianjmurrell** [comment]
Yeah, I get nothing.  I can see the REGISTER in the flexisip log but nothing at the Asterisk server.

What exactly in the flexisip.log is supposed to tell flexisip where to forward REGISTER requests?

Any chance you'd attach a log snippet from flexisip of your client registering to it and it registering to Asterisk so that I might see where mine is going wrong?

**Comment by driesken** [comment]
I suppose flexisip reads this from the VIA header in the REGISTER. Have you configured linphone to register using udp or tcp? Maybe choose a non-ambigious port for flexisip instead of 5060/5061?

Sure, but I'm out of office atm so I can share those tomorrow.

**Comment by brianjmurrell** [comment]
The Via: header from my linphone client looks like:

```
Via: SIP/2.0/TCP 10.75.22.32:36560;alias;branch=z9hG4bK.RQlh0cRqj;rport
```

so I don't see anything there that would tell flexisip where Asterisk is.

**Comment by driesken** [comment]
Sorry, not the VIA header. That contains the device's IP address. The REGISTER is directed to the host in the IP fragment itself:
`2019-04-03 09:10:57:200 flexisip-debug-Sending Request SIP message to sip:10.75.22.8:5060
REGISTER sip:pbx-mobile.example.com SIP/2.0`

Also, I can see signs of ipv6 in those? You could try to disable this within Linphone and flexisip. Could you post a redacted version of your config perhaps?

**Comment by brianjmurrell** [comment]
Hrm.  I'm not even getting that any more, using a modified (for local) [flexisip.conf from @SafeSoft-tlt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt).

I might have to see what I had back on April 03.

**Comment by driesken** [comment]
> Hrm. I'm not even getting that any more, using a modified (for local) [flexisip.conf from @SafeSoft-tlt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt).
> 
> I might have to see what I had back on April 03.

You could try my config posted above. Mine also makes use of the ContactRouteInserter:

> "The purpose of the ContactRouteInserter module is to masquerade the contact header of incoming registers that are not handled locally (think about flexisip used as a SBC gateway) in such a way that it is then possible to route back outgoing invites to the original address. It is a kind of similar mechanism as Record-Route, but for REGISTER.

**Comment by brianjmurrell** [comment]
@driesken Ahhh, sorry.  It is yours that I am using in fact.  And it's quite close to what I had back on Apr. 03.

**Comment by brianjmurrell** [comment]
> Because in Flexisip there is an error in the latest versions. Module [module :: PushNotification] is disabled!

@SafeSoft-tlt Can you expand on the above?  Not that I think it's relevant to my issues, but would be good to know what you think is broken in any case.

**Comment by SafeSoft-tlt** [comment]
> > Потому что в Flexisip есть ошибка в последних версиях. Модуль [module :: PushNotification] отключен!
> 
> @SafeSoft-tlt вы можете расширить выше? Не то, чтобы я думаю, что это имеет отношение к моим проблемам, но было бы хорошо знать, что вы думаете, сломано в любом случае.

I had a working version of Flexisip installed in March of this year. In June, I installed a new version of Flexisip with the same flexisip.conf file and push notifications stopped working for me. I found the working March version: bc-flexisip = 1.0.13-198

**Comment by SafeSoft-tlt** [comment]
> > Because in Flexisip there is an error in the latest versions. Module [module :: PushNotification] is disabled!
> 
> @SafeSoft-tlt Can you expand on the above? Not that I think it's relevant to my issues, but would be good to know what you think is broken in any case.

I had a working version of Flexisip installed in March of this year. In June, I installed a new version of Flexisip with the same flexisip.conf file and push notifications stopped working for me. I found the working March version: bc-flexisip = 1.0.13-198

**Comment by brianjmurrell** [comment]
@SafeSoft-tlt Have you filed a ticket about it?

**Comment by SafeSoft-tlt** [comment]
Every week they publish new versions, half of them with errors. How can I help them?

**Comment by brianjmurrell** [comment]
Filing tickets with your findings so that they know.

**Comment by driesken** [comment]
Could [this be fixed](https://github.com/BelledonneCommunications/flexisip/commit/3ba0a222f49e93ed6151ab440fe02c776d63c85f) a few minutes ago? I'll have to wait for the rpm to appear in the repo.

**Comment by SafeSoft-tlt** [comment]
How did you manage to solve the problem of 32 seconds?


> > Hrm. I'm not even getting that any more, using a modified (for local) [flexisip.conf from @SafeSoft-tlt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt).
> > I might have to see what I had back on April 03.
> 
> You could try my config posted above. Mine also makes use of the ContactRouteInserter:
> 
> > "The purpose of the ContactRouteInserter module is to masquerade the contact header of incoming registers that are not handled locally (think about flexisip used as a SBC gateway) in such a way that it is then possible to route back outgoing invites to the original address. It is a kind of similar mechanism as Record-Route, but for REGISTER.

https://github.com/BelledonneCommunications/linphone-android/issues/150#issuecomment-440966225

**Comment by brianjmurrell** [comment]
I have a configuration which accepts the REGISTER (on port 5061) from my linphone instance but it then proceeds to forward that registration to itself and not the Asterisk on the same machine on port 5060.

Given that I have told linphone to register to my PBX on port 5061 where flexisip is how is flexisip supposed to know that it's proxying for the Asterisk on the same machine on port 5060?  What is my missing link to get flexisip to forward to Asterisk on 5060 and not itself on 5061?

**Comment by driesken** [comment]
> How did you manage to solve the problem - 32 seconds?
> [BelledonneCommunications/linphone-android#150 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/150#issuecomment-440966225)
> 
> > > Hrm. I'm not even getting that any more, using a modified (for local) [flexisip.conf from @SafeSoft-tlt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt).
> > > I might have to see what I had back on April 03.
> > 
> > 
> > You could try my config posted above. Mine also makes use of the ContactRouteInserter:
> > > "The purpose of the ContactRouteInserter module is to masquerade the contact header of incoming registers that are not handled locally (think about flexisip used as a SBC gateway) in such a way that it is then possible to route back outgoing invites to the original address. It is a kind of similar mechanism as Record-Route, but for REGISTER.
> 
> [BelledonneCommunications/linphone-android#150 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/150#issuecomment-440966225)

I didn't. The problem with my setup is that there is only one-way audio after call setup. When I pause and resume the call, audio in both ways is working. Also can't seem to figure out why there is no attempt at push.

**Comment by brianjmurrell** [comment]
I also have no push attempts from my configuration.

https://lists.nongnu.org/archive/html/flexisip-developers/2019-07/msg00008.html

**Comment by SafeSoft-tlt** [comment]
> > How did you manage to solve the problem - 32 seconds?
> > [BelledonneCommunications/linphone-android#150 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/150#issuecomment-440966225)
> > > > Hrm. I'm not even getting that any more, using a modified (for local) [flexisip.conf from @SafeSoft-tlt](https://github.com/BelledonneCommunications/flexisip/files/3350009/flexisip.txt).
> > > > I might have to see what I had back on April 03.
> > > 
> > > 
> > > You could try my config posted above. Mine also makes use of the ContactRouteInserter:
> > > > "The purpose of the ContactRouteInserter module is to masquerade the contact header of incoming registers that are not handled locally (think about flexisip used as a SBC gateway) in such a way that it is then possible to route back outgoing invites to the original address. It is a kind of similar mechanism as Record-Route, but for REGISTER.
> > 
> > 
> > [BelledonneCommunications/linphone-android#150 (comment)](https://github.com/BelledonneCommunications/linphone-android/issues/150#issuecomment-440966225)
> 
> I didn't. The problem with my setup is that there is only one-way audio after call setup. When I pause and resume the call, audio in both ways is working. Also can't seem to figure out why there is no attempt at push.
> 
> EDIT: disabled the transcoder and seems to be working. I'm not experiencing the 32 sec issue. Mostly this is due to a missing OK. I haven't figured out why there aren't any push attempts.

I have a push notification for Android. But with "db-implementation = redis" it works incorrectly.
After restarting flexisip, did you launch your Android app?

**Comment by SafeSoft-tlt** [comment]
> I have a configuration which accepts the REGISTER (on port 5061) from my linphone instance but it then proceeds to forward that registration to itself and not the Asterisk on the same machine on port 5060.
> 
> Given that I have told linphone to register to my PBX on port 5061 where flexisip is how is flexisip supposed to know that it's proxying for the Asterisk on the same machine on port 5060? What is my missing link to get flexisip to forward to Asterisk on 5060 and not itself on 5061?

[global]
transports=sips:*

[module::Forward]
route=sip:<asterisk IP>:5060

**Comment by SafeSoft-tlt** [comment]
[global]
transports=sips:*

[module::Forward]
route=sip:[asterisk IP]:5060

**Comment by SafeSoft-tlt** [comment]
Settings need to be made in the Proxy field of the application account. Proxy needs to be enabled.

> I also have no push attempts from my configuration.
> 
> https://lists.nongnu.org/archive/html/flexisip-developers/2019-07/msg00008.html

Filter remove:
[module::PushNotification]
enabled=true
filter=
timeout=0

_____
Settings need to be made in the Proxy field of the application account. Proxy needs to be enabled.

**Comment by brianjmurrell** [comment]
I have all of the above and still no push notifications.

**Comment by driesken** [comment]
Anyone who has made progress in getting push to work? If I run a test with flexisip_pusher, it works fine.

**Comment by brianjmurrell** [comment]
> Anyone who has made progress in getting push to work?

Nope.

> If I run a test with flexisip_pusher, it works fine.

Indeed.  I can push successfully all I want to linphone-android.  It's getting flexisip to actually send the push that is the problem.

And there appears to be zero help or advise from the developers either here or on the flexisip-developers list.  Unfortunately.

I've pretty much given up on flexisip and am pushing from Asterisk directly.

**Comment by dipenpatel235** [comment]
flexisip_pusher, it works fine.
but not working flexisip push on call.

Below is mine flexisip version

[root@sip ~]# flexisip -v
flexisip  version: 2.0.0-beta-13-g521ea70
sofia-sip version 1.13.41bc
Compiled with:
- SNMP
- Transcoder
- Redis
- Soci
- Protobuf
- Presence
- Conference

**Comment by Sterlin11** [comment]
@brianjmurrell  I am facing issue with the integration of Asterisk as backend server and flexisip as sip proxy, if possible could you please share the flexisip and Asterisk (pjsip.conf )file? ,so that I will compare with my configuration .
Thanks in advance

**Comment by brianjmurrell** [comment]
I was never able to get Flexisip to work as a proxy.  The configuration is too cryptic and/or undocumented (sufficiently).

**Comment by Sterlin11** [comment]
OMG,How did you managed to send push notification ??

**Comment by brianjmurrell** [comment]
I have some hackery around Asterisk that sends pushes.  It consists of an [AGI script](https://github.com/brianjmurrell/Android-push-for-Asterisk) and some asterisk configuration (i.e. AMI at least) that I probably don't remember the entirety of.

At this point in time, it's left to the reader to figure out how to make it all work.  PRs with some instructions if you figure it out are welcome.  Maybe one day I will get some time to document the entire set up.

**Comment by SafeSoft-tlt** [comment]
Do you have your own build of Linphone?Without this, you will not be able to push notifications. 20.07.2023, 19:01, "Brian J. Murrell" ***@***.***>: I have some hackery around Asterisk that sends pushes. It consists of an AGI script and some asterisk configuration (i.e. AMI at least) that I probably don't remember the entirety of.At this point in time, it's left to the reader to figure out how to make it all work. PRs with some instructions if you figure it out are welcome. Maybe one day I will get some time to document the entire set up.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by brianjmurrell** [comment]
@SafeSoft-tlt Yes, of course.  As you say, you need to build your own linphone to bake in your own FCS account number.

**Comment by SafeSoft-tlt** [comment]
This is what I found in my archive. It's hard for me to remember what I was doing there. There is even a source on GitHub. Look for my name and there will be a link. The code is old.Message ID: ***@***.***>

**Comment by SafeSoft-tlt** [comment]
[global]debug=truelog-level=debugsyslog-level=debuguser-errors-logs=truedump-corefiles=trueauto-respawn=truealiases=localhost <local ip here>default-servers=proxytransports=sip:*tls-certificates-dir=/etc/flexisip/tls/tls-ciphers=HIGH:!SSLv2:!SSLv3:!TLSv1:!EXP:!ADH:!RC4:!3DES:!aNULL:!eNULLidle-timeout=3600keepalive-interval=1800proxy-to-proxy-keepalive-interval=0require-peer-certificate=falsetransaction-timeout=32000udp-mtu=1460enable-snmp=trueunique-id=plugins-dir=/opt/belledonne-communications/lib64/flexisip/plugins/plugins=[cluster]enabled=falsecluster-domain=nodes=internal-transport=sip:%auto:5059;transport=tcp[mdns-register]enabled=falsemdns-priority=0mdns-weight=100mdns-ttl=3600[event-logs]enabled=falselogger=filesystemdir=/var/log/flexisipdatabase-backend=mysqldatabase-connection-string=db='mydb' user='myuser' password='mypass' host='myhost.com'database-max-queue-size=100database-nb-threads-max=10[monitor]enabled=falsetest-interval=30logfile=/var/log/flexisip/flexisip_monitor.logswitch-port=12345password-salt=[stun-server]enabled=falsebind-address=0.0.0.0port=3478[presence-server]enabled=falsetransports=sip:127.0.0.1:5065;transport=tcpexpires=600notify-limit=200leak-detector=falselong-term-enabled=truebypass-condition=falseexternal-list-subscription-request=soci-connection-string=max-thread=50max-thread-queue-size=50[conference-server]enabled=falsetransport=sip:127.0.0.1:6064;transport=tcpconference-factory-uri=enable-one-to-one-chat-room=trueoutbound-proxy=sip:127.0.0.1:5060;transport=tcpdatabase-backend=mysqldatabase-connection-string=db='mydb' user='myuser' password='mypass' host='myhost.com'check-capabilities=true[module::DoSProtection]enabled=falsefilter=time-period=3000packet-rate-limit=20ban-time=2iptables-chain=FLEXISIP[module::SanityChecker]enabled=truefilter=[module::GarbageIn]enabled=truefilter=false[module::NatHelper]enabled=falsefilter= !(user-agent contains 'No NatHelper')contact-verified-param=verifiedfix-record-routes=truefix-record-routes-policy=safe[module::Authentication]enabled=falsefilter=auth-domains=*trusted-hosts=db-implementation=socisoci-password-request=select password, 'MD5' from flexisip where login = :id and domain = :domainsoci-user-with-phone-request=soci-users-with-phones-request=soci-connection-string=db=asterisk user=root password='root1234' host=astp3.internal.uzgent.besoci-backend=mysqlsoci-poolsize=100soci-max-queue-size=1000available-algorithms=MD5hashed-passwords=truenonce-expires=3600cache-expire=1800no-403=falsetrusted-client-certificates=new-auth-on-407=falseenable-test-accounts-creation=falsedisable-qop-auth=false[module::Redirect]enabled=falsefilter=contact=[module::Presence]enabled=falsefilter=is_request && (request.method-name == 'PUBLISH' || request.method-name == 'NOTIFY' || request.method-name == 'SUBSCRIBE')presence-server=sip:127.0.0.1:5065;transport=tcponly-list-subscription=falsecheck-domain-in-presence-results=false[module::Registrar]enabled=truefilter=reg-domains=*reg-on-response=truemax-contacts-by-aor=12unique-id-parameters=+sip.instance pn-tok linemax-expires=86400min-expires=60force-expires=-1static-records-file=static-records-timeout=600db-implementation=internalredis-server-domain=localhostredis-server-port=6379redis-auth-password=redis-server-timeout=1500redis-record-serializer=protobufredis-slave-check-period=60service-route=<asterisk IP>name-message-expires=message-expiresregister-expire-randomizer-max=0[module::StatisticsCollector]enabled=falsefilter=is_request && request.method-name == 'PUBLISH'collector-address=[module::Router]enabled=truefilter=(is_request && request.uri.params contains 'doroute') || is_responseuse-global-domain=falsefork=truestateful=truefork-late=truefork-no-global-decline=falsetreat-decline-as-urgent=falsetreat-all-as-urgent=falsecall-fork-timeout=90call-fork-urgent-timeout=5call-fork-current-branches-timeout=10call-push-response-timeout=0message-fork-late=truemessage-delivery-timeout=3600message-accept-timeout=15fallback-route=allow-target-factorization=falsegenerated-contact-route=generated-contact-expected-realm=generate-contact-even-on-filled-aor=falseremove-to-tag=preroute=resolve-routes=trueparent-domain-fallback=false[module::PushNotification]enabled=truefilter=timeout=0max-queue-size=100time-to-live=2592000apple=falseapple-certificate-dir=/etc/flexisip/apngoogle=falsegoogle-projects-api-keys=firebase=truefirebase-projects-api-keys=<PUSH API KEYS HERE>windowsphone=falsewindowsphone-package-sid=windowsphone-application-secret=no-badge=falseexternal-push-uri=external-push-method=GET[module::MediaRelay]enabled=falsefilter=nortpproxy=nortpproxysdp-port-range-min=1024sdp-port-range-max=65535bye-orphan-dialogs=falsemax-calls=0force-relay-for-non-ice-targets=trueprevent-loops=falseearly-media-relay-single=truemax-early-media-per-call=0inactivity-period=3600force-public-ip-for-sdp-masquerading=false[module::Transcoder]enabled=truefilter=jb-nom-size=0rc-user-agents=audio-codecs=pcma/8000 gsm/8000 telephone-event/8000remove-bw-limits=falseblock-retransmissions=false[module::Forward]enabled=truefilter=route=sip:<asterisk IP>:5060add-path=truerewrite-req-uri=falsedefault-transport=tcpparams-to-remove=pn-tok pn-type app-id pn-msg-str pn-call-str pn-call-snd pn-msg-snd pn-timeout[inter-domain-connections]accept-domain-registrations=falseassume-unique-domains=falsedomain-registrations=/etc/flexisip/domain-registrations.confverify-server-certs=truekeepalive-interval=30reg-when-needed=false[module::ContactRouteInserter]enabled=true#insert-domain=truemasquerade-contacts-on-registers=truemasquerade-contacts-for-invites=falseinsert-domain=false20.07.2023, 21:29, "Brian J. Murrell" ***@***.***>:
@SafeSoft-tlt Yes, of course.  As you say, you need to build your own linphone to bake in your own FCS account number.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
