### ISSUE TITLE
register from flexisip

### ISSUE THREAD

**Issue by mako16** [BelledonneCommunications/flexisip#6]
hi, i want to know how to make flexisip re-register to legacy platform, even if the phone turned off. we want  a call to send the invite to flexisip to force a push and wake up the linphone.
thanks

**Comment by ReisBenjamin** [comment]
Hello,

in order to keep the register when the phone is turned off we chose to use a very long keep alive (1 year) so that the contact is kept in DB and so flexisip can send the push

**Comment by mako16** [comment]
hi thanks for your response, but the problem is our legacy platform keeps registers for 3600 sec.
i cant change to one year. it is another workaround?
why dont flexisip continue with the register proces in less time.
Thanks

**Comment by mako16** [comment]
another question linphone needs to send the register for one year?

**Comment by prashantvidja** [comment]
linphone send expires time with contact-header so u need to change in linphone configuration file.
**Expires=<time in sec> **

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
