### ISSUE TITLE
flexisip_pusher command not found

### ISSUE THREAD

**Issue by secDaC** [BelledonneCommunications/flexisip#62]
Hi,

I want to test the flexisip push notification function for iOS.

If I type:
./flexisip_pusher --pntype apple --appid <bundle-id>.dev --pntok <tok> --debug
with the correct appid and the pntok
I get the error :flexisip_pusher "Command not found".

I use flexisip on Centos7.
What is the correct syntax to call the pusher?

**Comment by SafeSoft-tlt** [comment]
It is better to use third-party projects for this.
Also install: aptitude install bc-flexisip = 1.0.13-198
(it may be a bit earlier or later versions). Most new versions with Push stopped working altogether.

**Comment by willnaoosmith** [comment]
Using the command `find . -name flexisip_pusher`, i managed to find it at `/opt/belledonne-communications/bin/`
you can copy it to `/usr/bin/` and `/usr/sbin`, or create a link with `ln -s`

This issue can be closed now.
