### ISSUE TITLE
Build error rpm and deb packages for Ubuntu 

### ISSUE THREAD

**Issue by capitalfuse** [BelledonneCommunications/flexisip#64]
Build machine for
Linux ThinkPad-E450 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu18.04

**rpm package command is following;**

`./prepare.py flexisip-rpm -DENABLE_REDIS=ON -DENABLE_BC_HIREDIS=ON`

**error( wrote partially)**
```
Executing(%build): /bin/bash -e /var/tmp/rpm-tmp.rHQFpq
+ umask 022
+ cd /home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/rpmbuild/BUILD
+ cd bc-bctoolbox-0.6.0-166
+ %cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH:PATH=/opt/belledonne-communications -DENABLE_DECAF=0 -DENABLE_MBEDTLS=1 -DENABLE_POLARSSL=0 -DENABLE_SHARED=1 -DENABLE_STATIC=0 -DENABLE_STRICT=1 -DENABLE_TESTS=0 -DENABLE_TESTS_COMPONENT=0
/var/tmp/rpm-tmp.rHQFpq: line 28: fg: no job control
error: Bad exit status from /var/tmp/rpm-tmp.rHQFpq (%build)
```
I checked the above file /var/tpm/rpm-tmp.rHQpq, contents is below.

```
#!/bin/bash

  RPM_SOURCE_DIR="/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Build/bctoolbox"
  RPM_BUILD_DIR="/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/rpmbuild/BUILD"
  RPM_OPT_FLAGS="-O2 -g"
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/opt/belledonne-communications/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="bc-bctoolbox"
  RPM_PACKAGE_VERSION="0.6.0"
  RPM_PACKAGE_RELEASE="166.deb"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  RPM_BUILD_ROOT="/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/rpmbuild/BUILDROOT/bc-bctoolbox-0.6.0-166.deb.x86_64"
  export RPM_BUILD_ROOT
  
  PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/opt/belledonne-communications/lib/pkgconfig:/opt/belledonne-communications/share/pkgconfig"
  export PKG_CONFIG_PATH
  
  set -x
  umask 022
  cd "/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/rpmbuild/BUILD"
cd 'bc-bctoolbox-0.6.0-166'
%cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH:PATH=/opt/belledonne-communications  -DENABLE_DECAF=0 -DENABLE_MBEDTLS=1 -DENABLE_POLARSSL=0 -DENABLE_SHARED=1 -DENABLE_STATIC=0 -DENABLE_STRICT=1 -DENABLE_TESTS=0 -DENABLE_TESTS_COMPONENT=0
make -j4

exit $?
```
The cause of this error is the part of "%cmake . -DCMAKE_BUILD_TYPE ......." in line 28 which added "%" in front of "cmake".

if no "%" before "cmake", build process succeeded.

I want to clear why "%" added in front of "cmake" command.

**Comment by capitalfuse** [comment]
Installed the below(copy files to  /usr/lib/rpm directory)
**CMake builds use the the %cmake macro from the cmake-rpm-macros package.**
Fedora Rawhide for x86_64
https://rpmfind.net/linux/rpm2html/search.php?query=cmake-rpm-macros

**Comment by capitalfuse** [comment]
**Next error**
```
/usr/lib/rpm/find-debuginfo.sh: line 239: eu-strip: command not found
error: Bad exit status from /var/tmp/rpm-tmp.tFoBTp (%install)
```
**Resolved to install the following package**

> $ sudo apt install elfutils

**Comment by jehandelalune** [comment]
What about:
 docker run -v $PWD:/home/bc -it gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-ubuntu:18.04 ./prepare.py flexisip-rpm -DENABLE_REDIS=ON -DENABLE_BC_HIREDIS=ON

**Comment by capitalfuse** [comment]
Thnaks for your advice:jehandelalune. I made docker image and container by the following procedure.
```
docker run -v $PWD:/home/bc -it gitlab.linphone.org:4567/bc/public/linphone-sdk/bc-dev-ubuntu:18.04 ./prepare.py flexisip-rpm -DENABLE_REDIS=ON -DENABLE_BC_HIREDIS=ON
```
But need to copy files in cmake-rpm-macros into the container.
```
$ docker cp cmake.prov container_name:/usr/lib/rpm/cmake.prov
$ docker cp cmake.req container_name:/usr/lib/rpm/cmake.req
$ docker cp cmake.attr container_name:/usr/lib/rpm/fileattrs/cmake.attr
$ docker cp macros.cmake container_name:/usr/lib/rpm/macros.d/macros.cmake
```
then implement the shell command in the container. 
```
$ docker exec -it container_name bash
bc@9df842ffe3cf:/home/takanobu/git_projects/flexisip$ make
```
**Error** 
```
-- Build files have been written to: /home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Build/flexisip
make[4]: Entering directory '/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Build/flexisip'
Run CPack packaging tool for source...
CPack: Create package using TGZ
CPack: Install projects
CPack: - Install directory: /home/takanobu/git_projects/flexisip
CPack: Create package
CPack: - package: /home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Build/flexisip/bc-flexisip-1.0.13.tar.gz generated.
make[4]: Leaving directory '/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Build/flexisip'
[ 95%] Forcing build for 'EP_flexisip'
[ 97%] Performing build step for 'EP_flexisip'
error: File /home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Build/flexisip/bc-flexisip-1.0.13-0.tar.gz: No such file or directory
CMakeFiles/EP_flexisip.dir/build.make:117: recipe for target '/home/takanobu/git_projects/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build' failed
```
Doesn't match file name "bc-flexisip-1.0.13.tar.gz" with "bc-flexisip-1.0.13-0.tar.gz", "-0" added.

**Comment by capitalfuse** [comment]
Thanks jehandelalune. 
I have succeeded to build flexisip for ubuntu 18.04.
```
$ /home/takanobu/git_projects
$ git clone https://gitlab.linphone.org/BC/public/flexisip.git
$ docker container restart container_name
```
**in docker container:**
```
     # cd /home/takanobu/git*/flexisip
     # git submodule sync && git submodule update --init --recursive
     # ./prepare.py flexisip-rpm -DENABLE_REDIS=ON -DENABLE_BC_HIREDIS=ON
     # make
```

**Comment by hpng6** [comment]
i have followed above things. getting below errors

**cc1: out of memory allocating 28128160 bytes after a total of 137097216 bytes
src/CMakeFiles/bellesip.dir/build.make:1097: recipe for target 'src/CMakeFiles/bellesip.dir/grammars/belle_sip_messageParser.c.o' failed
make[6]: *** [src/CMakeFiles/bellesip.dir/grammars/belle_sip_messageParser.c.o] Error 1
make[6]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/rpmbuild/BUILD/bc-belle-sip-1.7.0'
CMakeFiles/Makefile2:108: recipe for target 'src/CMakeFiles/bellesip.dir/all' failed
make[5]: *** [src/CMakeFiles/bellesip.dir/all] Error 2
make[5]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/rpmbuild/BUILD/bc-belle-sip-1.7.0'
Makefile:154: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/rpmbuild/BUILD/bc-belle-sip-1.7.0'
error: Bad exit status from /var/tmp/rpm-tmp.gDtNNP (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.gDtNNP (%build)
CMakeFiles/EP_bellesip.dir/build.make:113: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_bellesip/EP_bellesip-build' failed
make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_bellesip/EP_bellesip-build] Error 1
make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
CMakeFiles/Makefile2:110: recipe for target 'CMakeFiles/EP_bellesip.dir/all' failed
make[2]: *** [CMakeFiles/EP_bellesip.dir/all] Error 2
make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
Makefile:14: recipe for target 'flexisip-rpm-build' failed
make: *** [flexisip-rpm-build] Error 2**

**Comment by BasilMVarghese** [comment]
> Installed the below package(copy files to /usr/lib/rpm directory)
> **CMake builds use the the %cmake macro from the cmake-rpm-macros package.**
> (Fedora Rawhide for x86_64)
> https://rpmfind.net/linux/rpm2html/search.php?query=cmake-rpm-macros

I copied those files. But the error appears again.

**Comment by BasilMVarghese** [comment]
> > Installed the below package(copy files to /usr/lib/rpm directory)
> > **CMake builds use the the %cmake macro from the cmake-rpm-macros package.**
> > (Fedora Rawhide for x86_64)
> > https://rpmfind.net/linux/rpm2html/search.php?query=cmake-rpm-macros
> 
> I copied those files. But the error appears again.

Installed the downloaded .rpm files using alien and solved the issue.

**Comment by hpng6** [comment]
> > > Installed the below package(copy files to /usr/lib/rpm directory)
> > > **CMake builds use the the %cmake macro from the cmake-rpm-macros package.**
> > > (Fedora Rawhide for x86_64)
> > > https://rpmfind.net/linux/rpm2html/search.php?query=cmake-rpm-macros
> > 
> > 
> > I copied those files. But the error appears again.
> 
> Installed the downloaded .rpm files using alien and solved the issue.

is presence server working and chat,calls history saving in database?

**Comment by BasilMVarghese** [comment]
> im using ubuntu 18.04 with docker image.
> 
> error: line 66: Unknown tag: %{systemd_requires}
> CMakeFiles/EP_flexisip.dir/build.make:120: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build' failed
> make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build] Error 1
> make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/EP_flexisip.dir/all' failed
> make[2]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
> make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> Makefile:83: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> Makefile:14: recipe for target 'flexisip-rpm-build' failed
> make: *** [flexisip-rpm-build] Error 2

Man, I am stuck with same error. Were you able to solve this ?

**Comment by hpng6** [comment]
> > im using ubuntu 18.04 with docker image.
> > error: line 66: Unknown tag: %{systemd_requires}
> > CMakeFiles/EP_flexisip.dir/build.make:120: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build' failed
> > make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build] Error 1
> > make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/EP_flexisip.dir/all' failed
> > make[2]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
> > make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > Makefile:83: recipe for target 'all' failed
> > make[1]: *** [all] Error 2
> > make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > Makefile:14: recipe for target 'flexisip-rpm-build' failed
> > make: *** [flexisip-rpm-build] Error 2
> 
> Man, I am stuck with same error. Were you able to solve this ?

i already escalate the issue. but still didn't get reply from the team...

**Comment by BasilMVarghese** [comment]
> > > im using ubuntu 18.04 with docker image.
> > > error: line 66: Unknown tag: %{systemd_requires}
> > > CMakeFiles/EP_flexisip.dir/build.make:120: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build' failed
> > > make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build] Error 1
> > > make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > > CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/EP_flexisip.dir/all' failed
> > > make[2]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
> > > make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > > Makefile:83: recipe for target 'all' failed
> > > make[1]: *** [all] Error 2
> > > make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > > Makefile:14: recipe for target 'flexisip-rpm-build' failed
> > > make: *** [flexisip-rpm-build] Error 2
> > 
> > 
> > Man, I am stuck with same error. Were you able to solve this ?
> 
> i already escalate the issue. but still didn't get reply from the team...

This is my first time with flexisip. I have a fresh 18.04 .  

Is there any working version of OS 16.04 or older, where Its already working fine.

**Comment by hpng6** [comment]
> > > > im using ubuntu 18.04 with docker image.
> > > > error: line 66: Unknown tag: %{systemd_requires}
> > > > CMakeFiles/EP_flexisip.dir/build.make:120: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build' failed
> > > > make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build] Error 1
> > > > make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > > > CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/EP_flexisip.dir/all' failed
> > > > make[2]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
> > > > make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > > > Makefile:83: recipe for target 'all' failed
> > > > make[1]: *** [all] Error 2
> > > > make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
> > > > Makefile:14: recipe for target 'flexisip-rpm-build' failed
> > > > make: *** [flexisip-rpm-build] Error 2
> > > 
> > > 
> > > Man, I am stuck with same error. Were you able to solve this ?
> > 
> > 
> > i already escalate the issue. but still didn't get reply from the team...
> 
> This is my first time with flexisip. I have a fresh 18.04 .
> 
> Is there any working version of OS. 16.04 or older, where Its already working fine.
> 
> Since its a fresh install, I can go with anything which will work.

can we talk private? skype hp.india

**Comment by capitalfuse** [comment]
Download **systemd-rpm-macros** from the following;
https://rpmfind.net/linux/rpm2html/search.php?query=systemd-rpm-macros&submit=Search+...&system=&arch=
And I adopted this:
https://rpmfind.net/linux/fedora/linux/releases/30/Everything/x86_64/os/Packages/s/systemd-rpm-macros-241-7.gita2eaa1c.fc30.noarch.rpm

In docker flexisip-sdk container, 
```
$ sudo cp macros.systemd /usr/lib/rpm/macros.d
```
That's it.
