### ISSUE TITLE
RPM build errors

### ISSUE THREAD

**Issue by shihabulmilah** [BelledonneCommunications/flexisip#69]
Hi All,

Anyone help me please, i get error when issued command "make"

 Bad exit status from /var/tmp/rpm-tmp.ate7Xy (%build)
CMakeFiles/EP_bctoolbox.dir/build.make:112: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_bctoolbox/EP_bctoolbox-build' failed
make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_bctoolbox/EP_bctoolbox-build] Error 1
make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
CMakeFiles/Makefile2:424: recipe for target 'CMakeFiles/EP_bctoolbox.dir/all' failed
make[2]: *** [CMakeFiles/EP_bctoolbox.dir/all] Error 2
make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
Makefile:14: recipe for target 'flexisip-rpm-build' failed
make: *** [flexisip-rpm-build] Error 2

Thanks

**Comment by hpng6** [comment]
same problem to me also

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
