### ISSUE TITLE
RTP packets problem on public IP server

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/flexisip#7]
I am trying to set up my server on public and static IP. Alice and Bob successfully register to my Flexisip server, but it's impossible  to make any call. I can see "Service Unavailable" on the Linphone App and the following lines:

"flexisip: getaddrinfo error: Name or service not known
ortp-message-Rtpsession bound to 192.168.1.8  ports [64006] [64007]
ortp-message-Rtpsession bound to 192.168.1.8  ports [17752] [17753]

in Flexisip logs.

When Alice and Bobs log in LAN everything works fine. Any idea of what is wrong with logging through WAN ?

**Comment by czaviar** [comment]
I managed to resolve the issue with logging (I used real domain name instead of an "virtual" one). But 
 now the problem is as following:

1. Alice and Bob log in succesfully.
2. Alice calls Bob, Bobs receives, but there is no RTP traffic (Download bandwidth shows 0).

The problem persists even if I completely  switch off the firewall (and turn on the DMZ option on my router).

**Comment by yuanlida** [comment]
I meet the same problem.

**Comment by Failxxx** [comment]
Hello,
Thank you for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
