### ISSUE TITLE
Call inbound drop in 32 sec

### ISSUE THREAD

**Issue by hpng6** [BelledonneCommunications/flexisip#70]
I deplyed flexisip but when I test my server with linphone application the call end after 30s and no audio and vidéo

**Comment by Anurag0987** [comment]
Hi did you manage to fix this, I am facing a similar issue in 2021, I have installed flexisip in my server and the call ends after 30 seconds and has no audio and video. The messaging only works and when I try to call to linphone.org domain everything works but It doesn't work with my server.
