### ISSUE TITLE
New version error for git submodule update --init --recursive

### ISSUE THREAD

**Issue by hpng6** [BelledonneCommunications/flexisip#72]
i'm
attaching the error logs here, please help me

root@28a3e681080f:/home/bc/flexisip# git submodule sync && git submodule update --init --recursive
Synchronizing submodule url for 'linphone-sdk'
Synchronizing submodule url for 'submodules/externals/hiredis'
Synchronizing submodule url for 'submodules/externals/jansson'
Synchronizing submodule url for 'submodules/externals/jose'
Synchronizing submodule url for 'submodules/externals/sofia-sip'
**error: Server does not allow request for unadvertised object e5fced7cb6315d023e1a5f44a1ba06be978a22aa
Fetched in submodule path 'linphone-sdk/msaaudio', but it did not contain e5fced7cb6315d023e1a5f44a1ba06be978a22aa. Direct fetching of that commit failed.
Failed to recurse into submodule path 'linphone-sdk'**

**Comment by dipenpatel235** [comment]
Submodule path 'submodules/externals/sofia-sip': checked out 'f0e76eb5fbca463a1fa62d1a135b62275347f3ef'
Unable to checkout '54acf9fb2404bb845a61ea89bc5d4b774658f7a8' in submodule path 'linphone-sdk'
