### ISSUE TITLE
error: line 66: Unknown tag: %{systemd_requires}

### ISSUE THREAD

**Issue by hpng6** [BelledonneCommunications/flexisip#73]
im using ubuntu 18.04 with docker image.

error: line 66: Unknown tag: %{systemd_requires}
CMakeFiles/EP_flexisip.dir/build.make:120: recipe for target '/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build' failed
make[3]: *** [/home/bc/flexisip/WORK/flexisip-rpm/Stamp/EP_flexisip/EP_flexisip-build] Error 1
make[3]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
CMakeFiles/Makefile2:351: recipe for target 'CMakeFiles/EP_flexisip.dir/all' failed
make[2]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
make[2]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/bc/flexisip/WORK/flexisip-rpm/cmake'
Makefile:14: recipe for target 'flexisip-rpm-build' failed
make: *** [flexisip-rpm-build] Error 2

**Comment by istiak101** [comment]
%{systemd_requires} is a rpm macro. It doesn't exist on your specific version of docker image.

https://github.com/redhat-openstack/easyfix/issues/23
https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
