### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by hpng6** [BelledonneCommunications/flexisip#74]
/opt/belledonne-communications/lib/libmediastreamer.so.10: undefined reference to `speex_echo_state_blob_new_from_memory'
/opt/belledonne-communications/lib/libmediastreamer.so.10: undefined reference to `speex_echo_state_blob_free'
/opt/belledonne-communications/lib/libmediastreamer.so.10: undefined reference to `speex_echo_state_blob_get_data'
/opt/belledonne-communications/lib/libmediastreamer.so.10: undefined reference to `speex_echo_state_blob_get_size'
collect2: error: ld returned 1 exit status
src/CMakeFiles/flexisip_server.dir/build.make:113: recipe for target 'src/flexisip' failed
make[6]: *** [src/flexisip] Error 1
make[6]: Leaving directory '/root/flexisip/WORK/flexisip/Build/flexisip'
CMakeFiles/Makefile2:146: recipe for target 'src/CMakeFiles/flexisip_server.dir/all' failed
make[5]: *** [src/CMakeFiles/flexisip_server.dir/all] Error 2
make[5]: Leaving directory '/root/flexisip/WORK/flexisip/Build/flexisip'
Makefile:151: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/root/flexisip/WORK/flexisip/Build/flexisip'
CMakeFiles/EP_flexisip.dir/build.make:120: recipe for target '/root/flexisip/WORK/flexisip/Stamp/EP_flexisip/EP_flexisip-build' failed
make[3]: *** [/root/flexisip/WORK/flexisip/Stamp/EP_flexisip/EP_flexisip-build] Error 2
make[3]: Leaving directory '/root/flexisip/WORK/flexisip/cmake'
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/EP_flexisip.dir/all' failed
make[2]: *** [CMakeFiles/EP_flexisip.dir/all] Error 2
make[2]: Leaving directory '/root/flexisip/WORK/flexisip/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/flexisip/WORK/flexisip/cmake'
Makefile:14: recipe for target 'flexisip-build' failed
make: *** [flexisip-build] Error 2

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
