### ISSUE TITLE
Persistent registration 

### ISSUE THREAD

**Issue by moisesynfam** [BelledonneCommunications/flexisip#76]
I have flexisip configured as front-end proxy for an Asterisk server to send push notifications. I would like to know how to configure flexisip to advertise registrations as always available no matter the real state of the connection with the device/app. Right know, if the device doesn't have internet connection or changes network without updating its registration in the new network there's no way for flexisip to locate this device and the asterisk server will drop the registration and further calls won't be processed resulting in no late forking. So if anyone could help I would appreciate it.

**Comment by 0x41mmarVM** [comment]
Ancient issue, but I just ran into this, so here is what I've found, if it's helpful to anyone:
One way of doing this is to force a very long expiry for registrations, example:
`
[module::Registrar]
max-expires=604800
min-expires=604800
`

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
