### ISSUE TITLE
bc-flexisip package not found on debian 9

### ISSUE THREAD

**Issue by karmac2015** [BelledonneCommunications/flexisip#79]
Hello,

I am trying to install flexisip on debian 9 using this [guide](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Installation/#HInstallationonDebian).

After executing the command :
`apt install bc-flexisip`
the following error appears in terminal:
> Unable to locate package bc-flexisip

Please, I need a solution to this problem

**Comment by 0x41mmarVM** [comment]
Rather than do:
`deb [arch=amd64] http://linphone.org/snapshots/debian stretch stable`
do
`deb [arch=amd64] http://linphone.org/snapshots/debian stretch main`

and that should do it.
