### ISSUE TITLE
Client interoperability - push notifications

### ISSUE THREAD

**Issue by loffler** [BelledonneCommunications/flexisip#8]
Hey guys,
I would like to develop a mobile SIP client that can use push notifications to notify about incoming calls.
So I wonder if I can design my client so it would work together with Flexisip's push notifications module, or is Flexisip intended to be used with Linphone clients only.

I have looked through the [linphone-android's source code](https://github.com/BelledonneCommunications/linphone-android/blob/4b395acd7542186885b88a323a61430f335eaef5/src/android/org/linphone/LinphonePreferences.java#L1168) and it seems to me, that I only need: 

- to send _app-id_ and _pn-type_ parameters within REGISTER messages,
- and to make my app "wake up"  on incoming push notification, so it could receive subsequent Invite message from Flexisip.

Would it be sufficient to work? If that matters, I'm going to use SIP.js to develop the client.
Thanks.

**Comment by DatBewar** [comment]
Hello,
Yes it's must be sufficient on flexisip side.
