### ISSUE TITLE
Flexisip build failedon debian 10

### ISSUE THREAD

**Issue by iggant** [BelledonneCommunications/flexisip#80]
```
[  7%] Linking CXX shared library libmediastreamer.so
make[5]: Leaving directory '/root/flexisip/WORK/flexisip/Build/ms2'
[ 88%] Built target mediastreamer
make[5]: Entering directory '/root/flexisip/WORK/flexisip/Build/ms2'
make[5]: Leaving directory '/root/flexisip/WORK/flexisip/Build/ms2'
make[5]: Entering directory '/root/flexisip/WORK/flexisip/Build/ms2'
[ 89%] Linking CXX executable mediastreamer2_tester
/usr/bin/ld: //lib/x86_64-linux-gnu/libpng16.so.16: undefined reference to `inflateValidate@ZLIB_1.2.9'
collect2: error: ld returned 1 exit status

```

**Comment by pdarcos** [comment]
Confirmed. It seems Flexisip is unusable on Debian 10.

No debian packages available and compilation also fails :(

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
