### ISSUE TITLE
Compile error in registrardb-redis-async.cc

### ISSUE THREAD

**Issue by SibertDekimo** [BelledonneCommunications/flexisip#82]
I have tried to compile flexisip using the included flex-from-src
 dockerfile. I am running into the following error:
`#9 2.271 /flexisip/src/registrardb-redis-async.cc: In member function 'void flexisip::RegistrarDbRedisAsync::handleFetch(redisReply*, flexisip::RegistrarUserData*)':
#9 2.271 /flexisip/src/registrardb-redis-async.cc:815:8: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
#9 2.271    LOGD("GOT fs:%s [%lu] --> %lu contacts", key, data->token, (reply->elements / 2));
#9 2.271         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    ~~~~~~~~~~~~~~~~~~~~~
`

I managed to continue compiling by changing line 815 to
`LOGD("GOT fs:%s [%lu] --> %lu contacts", key, data->token, (unsigned long)(reply->elements / 2));`

**Comment by Failxxx** [comment]
Hello,
Thank your for taking time to report a problem with Flexisip.

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
