### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by ugintl** [BelledonneCommunications/flexisip#86]
Is there any easy to follow guide to install flexisip server and build linphone clients/sdks? I have searched a lot, but haven't found anything except https://ficus.myvnc.com/en/blog/SIP%20Server%20Flexisip%20Build%20and%20Install_b85

Is this the best guide available out there? If yes, can you please explain some steps to me. I would prefer a guide without docker because I have not used it before.

It would be great to have such installation guides for people to follow and easily self host flexisip and build linphone sdk. I am specifically interested in android and ios. Let us say I have a domain "mydomain.com"

**Comment by altring** [comment]
You can check this one: [https://itgala.xyz/flexisip-installation-and-configuration-on-debian-9/](https://itgala.xyz/flexisip-installation-and-configuration-on-debian-9/)

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
