### ISSUE TITLE
Flexisip Conference Server

### ISSUE THREAD

**Issue by mayjethva** [BelledonneCommunications/flexisip#88]
Hi,

We are attempting to build the conference server on Flexisip but am not able to get it functioning.  We are not able to get the 3 headed icon in Linphone to start group chats.

We found a comment which stated LIME chat server requires a subscription.  Does this mean we are required to purchase a subscription from BelledonneCommunications or can we build this chat server on our own server?  Does the LIME chat only work through BelledonneCommuncations servers?

We have spent a lot of time on this without resolving the issue.  Help would be appreciated.

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
