### ISSUE TITLE
Can flexisip remember missed calls?

### ISSUE THREAD

**Issue by 0x41mmarVM** [BelledonneCommunications/flexisip#90]
Hi, this might be more related to SIP than Flexisip, or might be a dumb question, so apologies in advance.

If I try to call a number that's not currently connected, and thus the call times out or fails, would they be able to know once they register again?

I'm trying to use Flexisip with my own deployment of Linphone/ios, and since iOS13 push notifications have not been working. This would be fine if users could see who tried to call them once they manually open the app, but they don't. Missed calls only appear if they were missed while the app is open or running in the background (which with iOS is barely 3 minutes after you close the app) Is this normal? is there a way to change it?

Thanks.

[flexisip.conf.zip](https://github.com/BelledonneCommunications/flexisip/files/4452798/flexisip.conf.zip)

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
