### ISSUE TITLE
trusted-hosts problem in Authentication Section on Flexisip.conf

### ISSUE THREAD

**Issue by spytron** [BelledonneCommunications/flexisip#94]
I installed every piece of flexisip and I was trying to connect by using linphone android so when I run android app cannot see Connected on Top just seeing Connection in Progress warning and brown light not green.. So When I looked the C++ codes of flexisip core I saw trusted hosts and I changed the parameter in flexisip.conf Authentication section like trusted-hosts=IP addres of android device. so it worked !.. But I m asking this: Do I have to add every IP of the device to work with flexisip !? thats insane .. How to solve this?

**Comment by spytron** [comment]
if I disable Authentication it works well ! but is this right?

**Comment by spytron** [comment]
I think if you are not using TLS stuff then disable authentication mechanism so you dont have to worry about it because it is using digest auth and xmlrpc call to web site and so on.. I can see it from logs .. 
just wanted to explain it might be useful for somebody..

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
