### ISSUE TITLE
baresip and flexisip

### ISSUE THREAD

**Issue by holdenc** [BelledonneCommunications/flexisip#95]
Hi,

I am trying to use a cli application called [baresip](https://github.com/alfredh/baresip) to connect a free linphone.org account. Although the registration process seems to work fine, I am not able to receive any incoming call, but I can successfully dial outgoing calls.

I reported the bug against baresip [here](https://github.com/alfredh/baresip/issues/974) but it was suggested that I also flag it against flexisip. The bugreport there contains a trace of the SIP messages exchanged during the registration process.

Does anyone have an idea of what could be the cause of this issue?

**Comment by JarbasAl** [comment]
running into same issue, i made a python wrapper for baresip, see [here](https://github.com/JarbasAl/baresipy), and I am making a skill for mycroft, see [here](https://github.com/JarbasSkills/skill--voip)

i use linphone in my android phone, id rather recommend linphone than warn against using it

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
