### ISSUE TITLE
flexisip_monitor.py : ImportError: cannot import name __version__

### ISSUE THREAD

**Issue by kilanny** [BelledonneCommunications/flexisip#99]
```
pip install linphone

 /opt/belledonne-communications/bin/flexisip_monitor.py
Traceback (most recent call last):
  File "/opt/belledonne-communications/bin/flexisip_monitor.py", line 29, in <module>
    import linphone
  File "/usr/local/lib/python2.7/dist-packages/linphone/__init__.py", line 2, in <module>
    from linphone import __version__
ImportError: cannot import name __version__

```

Note: I cannot find any files in snapshots https://www.linphone.org/snapshots/linphone-python/linux-x86_64/linphone-latestlinux_x86_64.whl-test-report/ as many other solutions suggest

**Comment by Failxxx** [comment]
Hello,

I'm closing this ticket as it is probably out of date.
However, if you are still facing this issue, please feel free to reopen this ticket.
In this case, please make sure to provide clear and precise information (e.g. explanation, software versions, logs, etc.).

Sincerely,
Félix.
